<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<script language="javascript">
function trim(str, chars) {
	return ltrim(rtrim(str, chars), chars);
}
 
function ltrim(str, chars) {
	chars = chars || "\\s";
	return str.replace(new RegExp("^[" + chars + "]+", "g"), "");
}
 
function rtrim(str, chars) {
	chars = chars || "\\s";
	return str.replace(new RegExp("[" + chars + "]+$", "g"), "");
}
</script>
<div class="from-add-01">
<form name="frmAddVacancy" action="/vacancy/vacancy/add-vacancy" method="post">
<input type="hidden" name="vacancy_id" id="vacancy_id" value="<?php echo $this->vacancy_id;?>"> 
	<h2 style="color:#848484;margin-left:20px;">ADD VACANCY</h2>
		<ul>
			<li>
				<label></label>
				<em class="error"></em>
			</li>
			<li>
				<label>Company:</label>
				<input type="text" name="company_id" id="company_id">
			</li>
			<li>
				<label>Job Title:</label>
				<input type="text" name="job_title" id="job_title" value="<?php echo $this->job_title; ?>">
			</li>
			<li>
				<label>Salary:</label>
				<input name="min_salary" type="text" id="min_salary" style="width:93px;" value="<?php echo $this->min_salary; ?>">
                <input name="max_salary" type="text" id="max_salary" style="width:93px;" value="<?php echo $this->max_salary; ?>"> USD		
			</li>
			
			<li>
				<label>Location:</label>
		        <input type="text" name="province" id="province">
			</li>
			<li>
				<label>Work Level:</label>
				<select name="work_level_id">
                	<option value="">Please select</option>
                    <?php echo $this->listWorkLevel;?>
                </select>
			</li>
			<li>
				<label>Function:</label>
                <input type="text" name="function" id="function" value="">

			</li>
			<li>
				<label>Status:</label>
				<select name="status" id="status" style="width:235px">
                	<option value="">Please select</option>
                    <option value="Open" <?php if ($this->status=='Open') echo 'selected' ?> >Open</option>
                    <option value="Close" <?php if ($this->status=='Close') echo 'selected' ?> >Close</option>
                </select>
			</li>
            <li>
                <label>Job Description &amp; Requirements:</label>
                <textarea name="desc_reqs" cols="40" rows="20" id="desc_reqs"><?php echo $this->desc_reqs;?></textarea>
            </li>
		</ul>

        
	<div align="center" style="width:992px;clear:both;">
		<input type="submit" name="btSave" id="btSave" value="Save" class="button01">&nbsp;&nbsp;&nbsp;
        <input type="submit" class="button01" name="btAdd" id="btAdd" value="Save &amp; Add"> &nbsp;&nbsp;&nbsp;
        <a href="/vacancy"><input type="button" name="button3" id="button3" value="Cancel" class="button02"></a>
	</div>
</form>
</div>

