<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<form name="frmAddVacancy" action="/vacancy/vacancy/add-vacancy" method="post">
<input type="hidden" name="vacancy_id" id="vacancy_id" value="<?php echo $this->vacancy_id;?>"> 
<table class="popup" width="80%" border="2" cellpadding="0" cellspacing="0" bordercolor="#CCCCCC" style="border-collapse:collapse">
  <tr>
    <td valign="top" style="padding:15px 15px 15px 15px"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><h3>ADD VACANCY</h3></td>
      </tr>
      <tr>
        <td height="10"></td>
      </tr>
      <tr>
        <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td bgcolor="#8DC54C" class="title_popup">VACANCY DETAILS</td>
            </tr>
          <tr>
            <td height="10"></td>
          </tr>
          <tr>
            <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="49%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td width="36%" align="right">&nbsp;</td>
                    <td width="4%">&nbsp;</td>
                    <td width="4%" bgcolor="#f4fde7">&nbsp;</td>
                    <td width="56%" bgcolor="#f4fde7">&nbsp;</td>
                  </tr>
                  <tr>
                    <td class="subtitle_popup"> Consultant:<span class="require">*</span></td>
                    <td>&nbsp;</td>
                    <td bgcolor="#f4fde7">&nbsp;</td>
                    <td bgcolor="#f4fde7">
                    <select name="consultant_id" id="consultant_id" style="width:150px">
                    	<option value="">Please select</option>
                     	<?php echo $this->list_consultant; ?>
                    </select>
                    </td>
                  </tr>


                  <tr>
                    <td class="subtitle_popup">Company:<span class="require">*</span></td>
                    <td>&nbsp;</td>
                    <td bgcolor="#f4fde7">&nbsp;</td>
                    <td bgcolor="#f4fde7"><select name="company_id" id="company_id" style="width:150px">
                      <option value="">Please select</option>
                      <?php echo $this->list_company; ?>
                    </select></td>
                  </tr>
                  <tr>
                    <td class="subtitle_popup">Job Title:<span class="require">*</span></td>
                    <td>&nbsp;</td>
                    <td bgcolor="#f4fde7">&nbsp;</td>
                    <td bgcolor="#f4fde7"><input type="text" name="job_title" id="job_title" style="width:230px" value="<?php echo $this->job_title; ?>"></td>
                  </tr>
                  <tr>
                    <td class="subtitle_popup"># of Vacancies:</td>
                    <td>&nbsp;</td>
                    <td bgcolor="#f4fde7">&nbsp;</td>
                    <td bgcolor="#f4fde7"><input name="no_of_vacancies" type="text" id="no_of_vacancies" style="width:60px" value="<?php echo $this->no_of_vacancies; ?>"></td>
                  </tr>
                  <tr>
                    <td class="subtitle_popup">Salary:<span class="require">*</span></td>
                    <td>&nbsp;</td>
                    <td bgcolor="#f4fde7">&nbsp;</td>
                    <td bgcolor="#f4fde7">
                      <input name="min_salary" type="text" id="min_salary" style="width:80px" value="<?php echo $this->min_salary; ?>">
                      <input name="max_salary" type="text" id="max_salary" style="width:80px" value="<?php echo $this->max_salary; ?>">
                      USD</td>
                  </tr>
                  <tr>
                    <td class="subtitle_popup">Estimated Salary:<span class="require">*</span></td>
                    <td>&nbsp;</td>
                    <td bgcolor="#f4fde7">&nbsp;</td>
                    <td bgcolor="#f4fde7" class="note_popup">
                      <input name="estimated_salary" type="text" id="estimated_salary" style="width:80px" value="<?php echo $this->estimated_salary; ?>">
                    USD (for internal reference only)</td>
                  </tr>
                  <tr>
                    <td class="subtitle_popup">Location:<span class="require">*</span></td>
                    <td>&nbsp;</td>
                    <td bgcolor="#f4fde7">&nbsp;</td>
                    <td bgcolor="#f4fde7"><div class="comboxtemplate_n" id="comboProvince" style="cursor:pointer;z-index:2" onclick="$('#subcontentadvprovince').attr('style','z-index:2; position:absolute;  border: 1px solid #C3DAF9;  width:750px; height: 300px; background-color:#ffffff; margin-top:21px; margin-left:-1px');">	
                                                <input type="text" readonly="readonly" name="targetProvince" id="targetProvince" style="padding-left:4px;border:0px; width: 175px; height:14px;cursor:pointer;" value="<?php echo $this->numprovince; ?>"  >
                                                <input type="hidden" name="hdProvince" value="<?php echo $this->listProvinceId; ?>" id="hdProvince">
                                            </div>
                                            <div  id="subcontentadvprovince" style="position:absolute; display:none; border: 1px solid #C3DAF9; width:750px; height: 250px; background-color:#ffffff; margin-top:21px; ">
                                                <div  style="overflow:auto;width:750px; height:300px; padding: 10px 10px 10px 10px;"><?php echo $this->listProvince; ?></div>	
                                                <div style="width: 750px;">
                                                    <table width="100%" cellpadding="0" cellspacing="0" style="margin-top:-23px; margin-left:-1px"><tr><td bgcolor="#c3daf9" >
                                                    <span style="float:left;">&nbsp;&nbsp;<a href="#" onclick="uncheckAllCheckbox('province_id','#targetProvince','#hdProvince');" style="text-decoration:none"><strong>Unselect All</strong></a></span>
                                                    <span style="float:right;"><a href="#" onclick="$('#subcontentadvprovince').hide();" style="text-decoration:none"><strong>Close</strong></a>&nbsp;&nbsp;</span>
                                                    </td></tr></table>
                                                </div>
                                            </div></td>
                  </tr>
                  <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td bgcolor="#f4fde7">&nbsp;</td>
                    <td bgcolor="#f4fde7" class="note_popup"><label id="lbhdProvince" ><?php echo $this->location;?></label></td>
                  </tr>
                  <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td colspan="2" bgcolor="#f4fde7">&nbsp;</td>
                  </tr>
                  <tr>
                    <td class="subtitle_popup">Work Level:<span class="require">*</span></td>
                    <td>&nbsp;</td>
                    <td bgcolor="#f4fde7">&nbsp;</td>
                    <td bgcolor="#f4fde7"><select name="work_level_id" id="work_level_id" style="width:150px">
                      <option value="">Please select</option>
                      <?php echo $this->listWorkLevel;?>
                    </select></td>
                  </tr>
                  <tr>
                    <td class="subtitle_popup">Function:<span class="require">*</span></td>
                    <td>&nbsp;</td>
                    <td bgcolor="#f4fde7">&nbsp;</td>
                    <td bgcolor="#f4fde7"><div class="comboxtemplate_n" id="comboFunction" style="cursor:pointer;z-index:1" onclick="$('#subcontentadvfunction').attr('style','position:absolute;  border: 1px solid #C3DAF9;  width:750px; height: 300px; background-color:#ffffff; margin-top:21px; margin-left:-1px');">	
                                                <input type="text" readonly="readonly" name="targetFunction" id="targetFunction" style="padding-left:4px;border:0px; width: 175px; height:14px;cursor:pointer;" value="<?php echo $this->numfunction;?>"  >
                                                <input type="hidden" name="hdFunction" value="<?php echo $this->listFunctionId;?>" id="hdFunction">
                                            </div>
                                            <div  id="subcontentadvfunction" style="position:absolute; display:none; border: 1px solid #C3DAF9; width:750px; height: 250px; background-color:#ffffff; margin-top:21px; ">
                                                <div  style="overflow:auto;width:750px; height:300px; padding: 10px 10px 10px 10px;"><?php echo $this->listfunction;?></div>	
                                                <div style="width: 750px;">
                                                    <table width="100%" cellpadding="0" cellspacing="0" style="margin-top:-23px; margin-left:-1px"><tr><td bgcolor="#c3daf9" >
                                                    <span style="float:left;">&nbsp;&nbsp;<a href="#" onclick="uncheckAllCheckbox('function_id','#targetFunction','#hdFunction');" style="text-decoration:none"><strong>Unselect All</strong></a></span>
                                                    <span style="float:right;"><a href="#" onclick="$('#subcontentadvfunction').hide();" style="text-decoration:none"><strong>Close</strong></a>&nbsp;&nbsp;</span>
                                                    </td></tr></table>
                                                </div>
                                            </div></td>
                  </tr>

                  <tr>
                    <td class="subtitle_popup">Public<span class="require">*</span></td>
                    <td>&nbsp;</td>
                    <td bgcolor="#f4fde7">&nbsp;</td>
                    <td bgcolor="#f4fde7">
                      <input type="radio" name="p" id="p" value="Yes" <?php if ($this->p=='Yes') echo 'checked'; ?> >
Yes, Public&nbsp;&nbsp;
<input type="radio" name="p" id="p" value="No" <?php if ($this->p=='No') echo 'checked'; ?> >
No, Confidential
</td>
                  </tr>
                  <tr>
                    <td class="subtitle_popup">Status:<span class="require">*</span></td>
                    <td>&nbsp;</td>
                    <td bgcolor="#f4fde7">&nbsp;</td>
                    <td bgcolor="#f4fde7"><select name="status" id="status" style="width:150px">
                      <option value="">Please select</option>
                      <option value="Open" <?php if ($this->status=='Open') echo 'selected' ?> >Open</option>
                      <option value="Close" <?php if ($this->status=='Close') echo 'selected' ?> >Close</option>
                    </select></td>
                  </tr>
                  <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td colspan="2" bgcolor="#f4fde7">&nbsp;</td>
                  </tr>
                </table></td>
                <td>&nbsp;</td>
                <td width="49%" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td bgcolor="#f4fde7" class="subtitle_popup">&nbsp;</td>
                  </tr>
                  <tr>
                    <td bgcolor="#f4fde7" class="subtitle_left">Job Description &amp; Requirements:</td>
                  </tr>
                  <tr>
                    <td bgcolor="#f4fde7" style="padding:10px 20px 20px 20px"><textarea name="desc_reqs" cols="50" rows="20" id="desc_reqs"><?php echo $this->desc_reqs;?></textarea></td>
                  </tr>
                </table></td>
              </tr>
            </table></td>
          </tr>
          <tr>
            <td height="5"></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td bgcolor="#8DC54C" class="title_popup">COMPANY INFORMATION</td>
          </tr>
          <tr>
            <td height="10"></td>
          </tr>
          <tr>
            <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="24%" valign="top" class="subtitle_popup">Company Information <br />
                  (will be shown with job postings):</td>
                <td width="4%">&nbsp;</td>
                <td width="36%">                  <textarea name="textfield6" cols="60" rows="5" id="textfield6">Company is an Executive Search & Recruitment agency in four main industries: consumer goods & services, finance & banking, ICT, and industrial; a division of NhanViet Management Group (NVM Group) and a partner of Glasford International, a global collaboration of independent executive search firms, operating successfully over 30 countries throughout Europe, the Americas, Middle East, Far-East & Africa.

Our client is <INSERT DESCRIPTION ABOUT THE COMPANY HERE>
                </textarea>                </td>
                <td width="36%" valign="top" class="note_popup">Notice:<strong> Updated information will be shown in all job postings of the same company.</strong></td>
              </tr>
            </table></td>
          </tr>
          <tr>
            <td height="5"></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td><hr></td>
      </tr>
      <tr>
        <td align="center"><input type="submit" name="btSave" id="btSave" value="Save" class="del_button">&nbsp;&nbsp;&nbsp;
          <input type="submit" class="add_button" name="btAdd" id="btAdd" value="Save &amp; Add">
          &nbsp;&nbsp;&nbsp;
          <input type="submit" name="button3" id="button3" value="Cancel" class="del_button" /></td>
      </tr>
    </table></td>
  </tr>
  <tr></tr>
</table>
</form>
<script language="javascript">
function trim(str, chars) {
	return ltrim(rtrim(str, chars), chars);
}
 
function ltrim(str, chars) {
	chars = chars || "\\s";
	return str.replace(new RegExp("^[" + chars + "]+", "g"), "");
}
 
function rtrim(str, chars) {
	chars = chars || "\\s";
	return str.replace(new RegExp("[" + chars + "]+$", "g"), "");
}
function uncheckAllCheckbox(cbname,txtName,hdField){
	$(txtName).val('Please select...');
	$(hdField).val('');
	$("input[name='"+cbname+"']").each(function(i,val) {
             this.checked = false;
    });
	$('#lb'+trim(hdField,'#')).html('');
}
function countCheck(cbname,txtName,hdField){
	num=0;
	$("input[name='"+cbname+"']:checked").each(function(i,val) {
		  if (num==0)
		  {
		  	str=$(this).val();
			strname=$(this).next().text();
		  }
		 else
		 {
		 	str=str+","+$(this).val();
			strname=strname+", "+$(this).next().text();
		 }
		
		num++;
    });
	if (num>0)
	{
		$(txtName).val(num+' items selected');
		$(hdField).val(str);
		$('#lb'+trim(hdField,'#')).html('Selected: '+strname);
		
	}
	else
	{
		$(txtName).val('Please select...');
		$(hdField).val();
		$('#lb'+trim(hdField,'#')).html('');
	}
}
</script>