<form name="frmAddContact" method="post" action="" onsubmit="return checkValid()">
<input type="hidden" name="company_id"  id="company_id" value="<?php echo $this->company_id; ?>"/>
<input type="hidden" name="contact_person_id"  id="contact_person_id" value="<?php echo $this->contact_person_id; ?>"/>

<div class="from-add-01">
<h3><?php echo $this->title_page; ?></h3>
<ul>
	<li>
		<label></label>
		<em class="error"></em>
	</li>
	<li>
		<label>Company Name:</label>
		<label><?php echo $this->cominfo['company_name_vn']; ?></label>
		<label><?php echo $this->cominfo['company_name_en']; ?></label>
	</li>
	<li>
		<label>Full Name:
			<em>*</em>
		</label>
		
			<select name="title" id="title" style="width:60px;">
				<option value="Mr.">Mr.</option>
				<option value="Mrs.">Mrs.</option>
				<option value="ms.">Ms.</option>
			</select>
			<input type="text" name="full_name" id="full_name" value="<?php echo $this->contactinfo['full_name']; ?>">
		
	</li>
	<li>
		<label>Job Title:
			<em>*</em>
		</label>
		<label><input type="text" name="job_title" id="job_title" value="<?php echo $this->contactinfo['job_title']; ?>"></label>
	</li>
	<li>
		<label>Tel:</label>
		<label><input type="text" name="tel" id="tel" value="<?php echo $this->contactinfo['tel']; ?>"></label>
	</li>
	<li>
		<label>Fax:</label>
		<label><input type="text" name="fax" id="fax" value="<?php echo $this->contactinfo['fax']; ?>"></label>
	</li>
	<li>
		<label>Mobile:</label>
		<label><input type="text" name="mobile" id="mobile" value="<?php echo $this->contactinfo['mobile']; ?>"></label>
	</li>
	<li>
		<label>Email:</label>
		<label><input type="text" name="email" id="email" value="<?php echo $this->contactinfo['email']; ?>"></label>
	</li>
	<li>
		<label>Address:</label>
		<label>
			<textarea name="address" rows="6" id="address" style="width:500px"><?php echo $this->address; ?></textarea>
		</label>
	</li>
	<li>
		<label></label>
		<input class="button02" type="button" name="btCancel" id="btCancel" value="Cancel" onclick="window.location='/company'"><?php if($this->contact_person_id==""){?> &nbsp;&nbsp;&nbsp;
		<input class="button01" type="submit" name="btAddmore" id="btAddmore" value="Save &amp; Add More" ><?php }?> &nbsp;&nbsp;&nbsp;
		<input class="button01" type="submit" name="btSave" id="btSave" value="Save">
	</li>
</ul>
</div>
</form>
<script>
function checkValid()
{
	var full_name = $("#full_name").val();
	var job_title = $("job_title").val();
    var email = $('#email').val();
   
    if(full_name == '' ||  job_title == ''){
        $('.error').html('Please input into field required (*)');
        return false;
    }

    var check = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
    if(!check.test(email))
    {
    	$('.error').html('please enter a valid email address');
    	return false;
    }
   
    return true;
}   
</script>