<?php foreach($this->paginator as $rs) :?>
	<div class="checkbox" style="margin-top:4px">
	  <input type="radio" name="company_id" id="company_id" value="<?php echo $rs['company_id']?>" onclick="getValueListCheckBox(this,document.frmCompanyList.company_id)"/>
	</div>
	<div class="name">
		<a href="#view_company" class="view_company" id="<?php echo $rs['company_id']?>">
		    <?php echo $rs['full_name_en'] ?>
        </a>
	</div>
	<div class="name">
		<a href="#view_company" class="view_company" id="<?php echo $rs['company_id']?>">
		    <?php echo $rs['full_name_vn'] ?>
        </a>
	</div>	
	<div class="name">
		<?php echo $rs['address'] ?>&nbsp;
	</div>
	<div class="name" style="width:100px">
		<?php echo $rs['tel'] ?>&nbsp;
	</div>
	<div class="name">
		<?php echo $rs['email'] ?>&nbsp;
	</div>
	<div class="name" style="width:100px">
		<a href="/company/add-company/company_id/<?php echo $rs['company_id'] ?>" class="editcom">Edit</a>
	</div>
	<div style="clear:both"></div>
<?php endforeach; ?>