<?php
$contact= new Default_Model_ContactPersonMapper();
$listContact = $contact->getListContact ($this->cominfo['company_id']);
?>
<input type="hidden" id="company_id" value="<?php echo $this->cominfo['company_id']; ?>">
<input type="hidden" id="contact_person_id" value="<?php echo $listContact['contact_person_id']; ?>">
<div style="height :50px;color : #848484; ">
<h2><?php echo $this->cominfo['full_name_vn']; ?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Address : <?php echo $this->cominfo['address']; ?></h2>
</div>
<div class="list-company clearfix">
	<div class="head">
		<div class="status" align="center">
			<h4>STT</h4>
		</div>
		<div class="fullName" align="center">
			<h4>Full Name</h4>
		</div>
		<div class="jobTitle" align="center">
			<h4>Job Title</h4>
		</div>
		<div class="viewtel" align="center">
			<h4>Tel</h4>
		</div>
		<div class="viewemail" align="center">
			<h4>Email</h4>
		</div>
		<div class="edit" align="center">
			<h4>Edit</h4>
		</div>
	</div>
	<div class="info-content">
	<?php
    $num=1;
	foreach($listContact as $rs){
    ?>
    <div class="status"><?php echo $num; ?></div>
    <div class="fullName" ><?php echo $rs['full_name'];?></div>
    <div class="jobTitle"><?php echo $rs['job_title'];?></div>
    <div class="viewtel" ><?php echo $rs['tel']; ?></div>
    <div class="viewemail"><?php echo $rs['email']; ?></div>
    <div class="edit"><a href="/company/add-contact/contact_person_id/<?php echo $rs['contact_person_id']; ?>">Edit</a></div>
    <?php $num++; }?>
    </div>
</div>
<div style="clear:both">&nbsp;</div>
<div align="center" style="clear:both">
	<input type="submit" name="close" class="button01"value="Close"
			onclick="event.preventDefault(); parent.$.fancybox.close();" />
</div>

