<div align="center" style="color:#1B7CBD;font-size:16px"><b>COMPANY DETAIL</b></div>
<table cellpadding="5" cellspacing="6">
	<tr>
		<td style="width:115px">Company Name</td>
		<td><b><?php echo $this->company->getCompanyName();?></b></td>
	</tr>
	<tr>
		<td>Busines Type</td>
		<td><?php echo $this->company->getBusinesType();?></td>
	</tr>                    
	<tr>
		<td>Tel</td>
		<td><?php echo $this->company->getTel();?></td>
	</tr>
	<tr>
		<td>Email</td>
		<td><?php echo $this->company->getEmail();?></td>
	</tr>
	<tr>
		<td>Address</td>
		<td><?php echo $this->company->getAddress();?></td>
	</tr>
	<tr>
		<td>Website</td>
		<td><?php echo $this->company->getWebsite();?></td>
	</tr>
    <tr>
        <td>Infomation</td>
        <td><?php echo $this->company->getInformation();?></td>
    </tr>
	<tr>
        <td>Assign Consultant</td>
        <td><?php echo $this->company->getAssignCons();?></td>
    </tr>
</table>
<div style="clear:both">&nbsp;</div>
<div align="center" style="position: absolute;bottom:0; padding-left:250px">
	<a href="/company/add-company/id/<?php echo $this->company->getCompanyId()?>" style="text-decoration:none;">
		<input type="button" name="edit" class="button01"value="Edit"/>
	</a>
    <input type="button" name="close" class="button01"value="Close"
            onclick="event.preventDefault(); parent.$.fancybox.close();" />
</div>
