<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<script>
function checkLogin(){
    $.ajax({
        url: '/resume/check-login',
        success: function(result){
            if(!result) document.location.href = '/user/login';
        }
   });
}
</script>
<div class="block-search">
<form id="frmsearch" action="/company/" method="post">
	<label>Search</label>
	<select name="ccode_id" id="ccode_id" style="width:125px">
        <option value="1" <?php if ($this->ccode_id==1) echo "selected";?> >Company Code</option>
	   <option value="2" <?php if ($this->ccode_id==2) echo "selected";?>>Company Name</option>
	</select>
	<input name="txtSearch" id="txtSearch" type="text" value="<?php echo $this->txtSearch; ?>"/>
	<select name="industry_id" style="width:120px">
	   <option value="0">Please select</option>
       <?php echo $this->list_industry; ?>
   </select>
            <input id="btSearch" name="btSearch" type="submit" value="Search" style="margin-right:420px"/>
              <input type="hidden" name="page" id="page" value="1" />
              
              <label for="choice">Sort : </label>
              <select name="short_name_id" id="short_name_id" style="width:80px">
			  <option value="full_name_en" <?php if ($this->short_name_id=="full_name_en") echo "selected";?>>Name</option>
              <option value="created_date" <?php if ($this->short_name_id=="created_date") echo "selected";?>>Created Date</option>
			</select>
            <select name="sort_type_id" id="sort_type_id" style="width:60px">
			  <option value="ASC" <?php if ($this->sort_type_id=="ASC") echo "selected";?>>ASC</option>
              <option value="DESC" <?php if ($this->sort_type_id=="DESC") echo "selected";?>>DESC</option>
			</select>
            <input id="button3" type="submit" value="Sort" />
</form>
</div>  <br />

<p class="today-entry" id="report">Month: Apr-2011 <a href="#">(Change)</a> | Open Vacancies: 18 | Candidates in Process: 20</p>
<br />
	<br />
	<a href="/company/company/add-company" style="text-decoration:none;">
		<input class="button01" type="button" value="Add Company" />
	</a>
        <input class="button01" type="button" value="Add Contact" onclick="addContact()"/>
    <br />
<br />
<form name="frmCompanyList">
<div id="box">   
    <div class="list-company clearfix">
        <div class="head">
            <div class="checkbox">
                &nbsp;
            </div>
            <div class="code">
                <h4>Code</h4>
            </div>
            <div class="name">
                <h4>Company</h4>
            </div>
            <div class="cons">
                <h4>Cons</h4>
            </div>
            <div class="action">
                <h4>action</h4>
            </div>
        </div>
        <div class="info-content">
        <?php echo $this->partial('index/list-company.phtml', array('paginator' => $this->paginator)); ?>
        </div>
    </div>
</div>
<div style="clear:both">&nbsp;</div>
  
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
	  <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
		  <tr>
			<td width="5%"><input id="button12" type="submit" value="Delete" class="del_button" /></td>
			<td width="90%">&nbsp;</td>
		  </tr>
	  </table></td>
	</tr>

	<tr>
	  <td></td>
	</tr>
	<?php if(count($this->paginator)) :?>
	<tr>
		<td align="center">
		<div id="box">
            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
		</div></td>
	</tr>
	<?php endif;?>
  </table>
<input type="radio" name="hdcompany_id" id="hdcompany_id" /> 
 </form>
 <div id="view_company" style="width:700px;height: 450px; overflow-y:scroll; display: none;">&nbsp;</div>
 
<script language="javascript">

 function addContact()
 {
	 if ($("#hdcompany_id").val()=="")
	 	alert("Please select company to add contact.")
	else
		window.location="company/company/add-contact/company_id/"+$("#hdcompany_id").val();
	
 }


 $(document).ready(function() {
     //Begin View detail candidate
     $(".view_company").fancybox();
     $(".view_company").click(function(){
         checkLogin();
         $('#view_company').html('');
         var company_id = $(this).attr('id');
         $.ajax({
             url: '/company/company/view-company',
             type: "POST",
             data: { 
            	 company_id: company_id, 
             },
             success: function(result) {
                 $('#view_company').html(result);
             }
         });
     });
     //End View detail candidate
 });

</script>