<?php
$company = $this->company;
$totalOpen=0;
$totalProcess=0;
foreach($this->list as $rs) :
	$numact=$company->countAct($rs['company_id']);
	$newVa=$company->countNewVacancy($rs['company_id']);
	$openVa=$company->countOpenVacancy($rs['company_id']);
	$numRsSent=$company->countRsProcess($rs['company_id'],1);
	$numInt1=$company->countRsProcess($rs['company_id'],2);
	$numInt2=$company->countRsProcess($rs['company_id'],"3,4,5,6,7");
	$numOffMade=$company->countRsProcess($rs['company_id'],9);
	$numOffAcpt=$company->countRsProcess($rs['company_id'],10);
	$numJoin=$company->countRsProcess($rs['company_id'],11);
	$numProcess=$company->countCanProcess($rs['company_id'],"1,2,3,4,5,6,7,8,9,10");
	$industry_name = $company->getFieldValue("industry_lookup","industry_id='".$rs['industry_id']."'","abbreviation");
	$consultant_id = $company->getFieldValue("com_has_consultant_incharge","company_id='".$rs['company_id']."'","consultant_id");
	$consultant_name = $company->getFieldValue("consultant","consultant_id='$consultant_id'","abbreviated_name");
?>
	<div class="checkbox">
	  <input type="radio" name="company_id" id="company_id" value="<?php echo $rs['company_id']?>" onclick="getValueListCheckBox(this,document.frmCompanyList.hdcompany_id)"/>
	</div>
	<div class="code">
		<?php echo $rs['company_code'] ?>
	</div>
	<div class="name">
		<h4><a href="#view_company" class="view_company" id="<?php echo $rs['company_id']?>"><?php echo $rs['full_name_en'] ?></a></h4>
	</div>
	<div class="ind">
		<b><?php echo $industry_name ?></b>
	</div>
	<div class="act">
		<?php echo $numact ?>
	</div>
	<div class="newva">
		<?php echo $newVa ?>
	</div>
	<div class="openva">
		<?php echo $openVa ?>
	</div>
	<div class="ressent">
		<?php echo $numRsSent ?>
	</div>
	<div class="inter">
		<?php echo  ($numInt1+$numInt2) ?>
	</div>
	<div class="offer">
		<?php echo $numOffMade ?>
	</div>
	<div class="accept">
		<?php echo $numOffAcpt ?>
	</div>
	<div class="joined">
		<?php echo $numJoin ?>
	</div>
	<div class="status">
		<?php echo $rs['status'] ?>
	</div>
	<div class="cons">
		<?php echo $consultant_name ?>
	</div>
	<div class="action">
		<a href="company/company/add-company/company_id/<?php echo $rs['company_id'] ?>" class="editcom">Edit</a>
	</div>
	<?php
		//echo $totalOpen += $openVa;
		//echo $totalProcess += $numProcess;
	?>
	<div style="clear:both">&nbsp;</div>
<?php endforeach; ?>