<div style="width:900px;height: 500px; display: none;" id="inline">
<form name="frmAvanSearch" id="frmAvanSearch" method="post" action="/resume/avandce-search" >
<table cellpadding="0" cellspacing="0" style="border-collapse: collapse">
    <tr>
        <td valign="top" style="padding: 15px 15px 15px 15px">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td>
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                        <td colspan="3" bgcolor="#990000" class="title_popup">
                            <img src="../img/icons/icon_expand.gif" width="9" height="9" /> SEARCH PERSONAL DETAILS
                        </td>
                    </tr>
                    <tr>
                        <td height="20" colspan="3"></td>
                    </tr>
                    <tr>
                        <td width="45%" valign="top">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td width="28%" align="right"></td>
                                <td width="4%"></td>
                                <td colspan="2" bgcolor="#FFECEC"></td>
                            </tr>
                            <tr>
                                <td class="subtitle_popup">Candidate Name:</td>
                                <td>&nbsp;</td>
                                <td width="5%" bgcolor="#FFECEC">&nbsp;</td>
                                <td width="63%" bgcolor="#FFECEC">
                                    <input type="text" name="full_name" id="full_name" style="width: 230px" />
                                </td>
                            </tr>
                            <tr>
                                <td class="subtitle_popup">Email:</td>
                                <td>&nbsp;</td>
                                <td bgcolor="#FFECEC">&nbsp;</td>
                                <td bgcolor="#FFECEC">
                                    <input type="text" name="email" id="email" style="width: 230px" />
                                </td>
                            </tr>
                            <tr>
                                <td class="subtitle_popup">Phone:</td>
                                <td>&nbsp;</td>
                                <td bgcolor="#FFECEC">&nbsp;</td>
                                <td bgcolor="#FFECEC">
                                    <input type="text" name="phone" id="phone" style="width: 230px" />
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td colspan="2" bgcolor="#FFECEC"></td>
                            </tr>
                        </table>
                        </td>
                        <td width="2%">&nbsp;</td>
                        <td width="53%" valign="top">
                        <table width="100%" border="0" cellspacing="0"
                            cellpadding="0">
                            <tr>
                                <td width="25%" align="right"></td>
                                <td width="4%"></td>
                                <td colspan="2" bgcolor="#FFECEC"></td>
                            </tr>
                            <tr>
                                <td class="subtitle_popup">Gender:</td>
                                <td>&nbsp;</td>
                                <td width="4%" bgcolor="#FFECEC">&nbsp;</td>
                                <td width="67%" bgcolor="#FFECEC">
                                    <input type="radio" name="radio" id="radio5" value="radio" />Male&nbsp;&nbsp;&nbsp; 
                                    <input type="radio" name="radio" id="radio6" value="radio" /> Female
                                </td>
                            </tr>
                            <tr>
                                <td class="subtitle_popup">Age:</td>
                                <td>&nbsp;</td>
                                <td bgcolor="#FFECEC">&nbsp;</td>
                                <td bgcolor="#FFECEC">
                                    <select name="select8" id="select8" style="width: 60px">
                                        <option>=</option>
                                    </select>
                                    <input name="textfield4" type="text" style="width: 80px" value="" />
                                </td>
                            </tr>
                            <tr>
                                <td valign="top" class="subtitle_popup">Marital
                                Status:</td>
                                <td>&nbsp;</td>
                                <td bgcolor="#FFECEC">&nbsp;</td>
                                <td bgcolor="#FFECEC"><input
                                    type="radio" name="radio" id="radio"
                                    value="radio" /> Single
                                &nbsp;&nbsp;&nbsp; <input type="radio"
                                    name="radio" id="radio2"
                                    value="radio" /> Married
                                &nbsp;&nbsp;&nbsp; <input type="radio"
                                    name="radio" id="radio2"
                                    value="radio" /> Divorced</td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td colspan="2" bgcolor="#FFECEC"></td>
                            </tr>
                        </table>
                        </td>
                    </tr>
                </table>
                </td>
            </tr>
            <tr>
                <td height="20"></td>
            </tr>
            <tr>
                <td>
                <table width="100%" border="0" cellspacing="0"
                    cellpadding="0">
                    <tr>
                        <td colspan="3" bgcolor="#990000"
                            class="title_popup"><img
                            src="../img/icons/icon_expand.gif" width="9"
                            height="9" /> SEARCH EXPERIENCE, SALARY,
                        WORK LOCATION</td>
                    </tr>
                    <tr>
                        <td height="20" colspan="3"></td>
                    </tr>
                    <tr>
                        <td width="45%" valign="top">
                        <table width="100%" border="0" cellspacing="0"
                            cellpadding="0">
                            <tr>
                                <td width="28%" align="right"></td>
                                <td width="4%"></td>
                                <td colspan="2" bgcolor="#FFECEC"></td>
                            </tr>
                            <tr>
                                <td class="subtitle_popup">Job Title:</td>
                                <td>&nbsp;</td>
                                <td width="5%" bgcolor="#FFECEC">&nbsp;</td>
                                <td width="63%" bgcolor="#FFECEC"><input
                                    type="text" name="textfield6"
                                    id="textfield6" style="width: 230px" /></td>
                            </tr>
                            <tr>
                                <td class="subtitle_popup">Company:</td>
                                <td>&nbsp;</td>
                                <td bgcolor="#FFECEC">&nbsp;</td>
                                <td bgcolor="#FFECEC"><input type="text"
                                    name="textfield6" id="textfield7"
                                    style="width: 230px" /></td>
                            </tr>
                            <tr>
                                <td class="subtitle_popup">Duties:</td>
                                <td>&nbsp;</td>
                                <td bgcolor="#FFECEC">&nbsp;</td>
                                <td bgcolor="#FFECEC"><input type="text"
                                    name="textfield6" id="textfield8"
                                    style="width: 230px" /></td>
                            </tr>
                            <tr>
                                <td class="subtitle_popup">&nbsp;</td>
                                <td>&nbsp;</td>
                                <td bgcolor="#FFECEC">&nbsp;</td>
                                <td bgcolor="#FFECEC"><input
                                    type="checkbox" name="checkbox"
                                    id="checkbox" /> Search last
                                experience only</td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td colspan="2" bgcolor="#FFECEC"></td>
                            </tr>
                            <tr>
                                <td colspan="4"></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td colspan="2" bgcolor="#FFECEC"></td>
                            </tr>
                            <tr>
                                <td class="subtitle_popup">Salary:</td>
                                <td>&nbsp;</td>
                                <td bgcolor="#FFECEC">&nbsp;</td>
                                <td bgcolor="#FFECEC"><select
                                    name="select3" id="select4"
                                    style="width: 60px">
                                    <option>=</option>
                                </select> <input name="textfield7"
                                    type="text" id="textfield11"
                                    style="width: 80px" value="" /> USD</td>
                            </tr>
                            <tr>
                                <td class="subtitle_popup">Work
                                Location:</td>
                                <td>&nbsp;</td>
                                <td bgcolor="#FFECEC">&nbsp;</td>
                                <td bgcolor="#FFECEC"></td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td bgcolor="#FFECEC">&nbsp;</td>
                                <td valign="bottom" bgcolor="#FFECEC"
                                    class="note_popup">Selected: HCMC,
                                Binh Duong</td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td colspan="2" bgcolor="#FFECEC"></td>
                            </tr>
                        </table>
                        </td>
                        <td width="2%">&nbsp;</td>
                        <td width="53%" valign="top">
                        <table width="100%" border="0" cellspacing="0"
                            cellpadding="0">
                            <tr>
                                <td width="25%" align="right"></td>
                                <td width="4%"></td>
                                <td colspan="2" bgcolor="#FFECEC"></td>
                            </tr>
                            
                            <tr>
                                <td class="subtitle_popup">&nbsp;</td>
                                <td>&nbsp;</td>
                                <td bgcolor="#FFECEC">&nbsp;</td>
                                <td valign="top" bgcolor="#FFECEC"
                                    class="note_popup">Selected: Manager</td>
                            </tr>
                            <tr>
                                <td class="subtitle_popup">Function:</td>
                                <td>&nbsp;</td>
                                <td bgcolor="#FFECEC">&nbsp;</td>
                                <td bgcolor="#FFECEC"><select
                                    name="select7" id="select7"
                                    style="width: 135px">
                                    <option></option>
                                </select> &nbsp;&nbsp;&nbsp; for <input
                                    name="textfield9" type="text"
                                    id="textfield10" style="width: 80px"
                                    value="" /> years</td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td colspan="2" bgcolor="#FFECEC"></td>
                            </tr>
                        </table>
                        </td>
                    </tr>
                </table>
                </td>
            </tr>
            <tr>
                <td height="20"></td>
            </tr>
            <tr>
                <td>
                <hr />
                </td>
            </tr>
            <tr>
                <td align="center">
                <input type="button" name="avansearch" id="avansearch" value="Search">&nbsp;&nbsp;&nbsp; 
                <input type="button" name="cancel" id="cancel" value="Cancel"  onclick="event.preventDefault(); parent.$.fancybox.close();"/></td>
            </tr>
        </table>
        </td>
    </tr>
    <tr></tr>
</table>
</form>
</div>