<?php echo $this->headScript ();?>
<?php echo $this->partial ( 'resume/menu-add-resume.phtml' )?>

<form id="form" action="/resume/save-expectation" method="post">
<table style="width:50%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td width="10%" align="right"></td>
        <td width="4%"></td>
        <td colspan="3" bgcolor="#FFECEC"></td>
    </tr>
    <tr>
        <td valign="top" class="subtitle_popup">Current Salary:</td>
        <td>&nbsp;</td>
        <td bgcolor="#FFECEC">&nbsp;</td>
        <td colspan="2" bgcolor="#FFECEC">
        	<input type="text" name="current_salary" value="<?php echo $this->expectationRowSet->getCurrentSalary();?>"/> USD
        </td>
    </tr>
    <tr>
        <td valign="top" class="subtitle_popup">Expected Salary:</td>
        <td>&nbsp;</td>
        <td bgcolor="#FFECEC">&nbsp;</td>
        <td colspan="2" bgcolor="#FFECEC">
        	<input type="text" name="estimated_salary_from" value="<?php echo $this->expectationRowSet->getEstimatedSalaryFrom();?>"/> 
            <input type="text" name="estimated_salary_to" value="<?php echo $this->expectationRowSet->getEstimatedSalaryTo();?>"/> USD</td>
    </tr>
	<tr>
        <td valign="top" class="subtitle_popup">Expected Location:</td>
        <td>&nbsp;</td>
        <td width="4%" bgcolor="#FFECEC">&nbsp;</td>
        <td width="25%" valign="top" bgcolor="#FFECEC">
            <input class="province" type="button" name="province" value="Province" />
            <div class="multiselect" style="display:none; position:fixed">
            	<div style="width:160px; float:left">
            <?php 
            $i = 1;
            foreach($this->listProvince as $province) :
            	if($i % 22 == 0): echo '</div><div style="width:160px; float:left">';endif;
            ?>
            	<label><input type="checkbox" name="option[]" value="<?php echo $province['province_id']?>" /> <?php echo $province['name']?></label>
                	
            <?php 
            $i++;
            endforeach;?>
            	</div>
           </div>
        </td>
    </tr>	
    <tr>
        <td></td>
        <td></td>
        <td colspan="3" bgcolor="#FFECEC"></td>
    </tr>
    <tr>
        <td colspan="5"></td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td colspan="3" align="center">
        	<input type="hidden" name="resume_id" value="<?php echo $this->resumeId; ?>" />
        	<input type="hidden" name="expecid" value="<?php echo $this->expectationRowSet->getResExpectationId();?>" />
        	<a href="/resume/experience/id/<?php echo $this->resumeId; ?>"><input type="button" name="button" value="Back" /></a>&nbsp;&nbsp; 
        	<input type="submit" name="button" value="Complete" />
        </td>
    </tr>
</table>
</form>
<script>
$(document).ready(function(){
    $(".province").click(function(){
        if(($(".multiselect").css('display')) == 'none') $(".multiselect").show('slow');
        else $(".multiselect").hide('slow');
    });
});

jQuery.fn.multiselect = function() {
    $(this).each(function() {
        var checkboxes = $(this).find("input:checkbox");
        checkboxes.each(function() {
            var checkbox = $(this);
            // Highlight pre-selected checkboxes
            if (checkbox.attr("checked"))
                checkbox.parent().addClass("multiselect-on");
 
            // Highlight checkboxes that the user selects
            checkbox.click(function() {
                if (checkbox.attr("checked"))
                    checkbox.parent().addClass("multiselect-on");
                else
                    checkbox.parent().removeClass("multiselect-on");
            });
        });
    });
};

$(".multiselect").multiselect();
</script>