<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<?php
echo $this->partial ( '/resume/menu-add-resume.phtml' )?>
<form name="frm" method="post" action="/resume/save-experience" onsubmit="return checkValid()">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td width="50%" valign="top">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td width="17%" align="right"></td>
                <td width="4%"></td>
                <td bgcolor="#FFECEC">&nbsp;</td>
                <td bgcolor="#FFECEC" id="error" class="error"></td>
            </tr>
            <tr>
                <td class="subtitle_popup">Start date:<span class="error">*</span></td>
                <td>&nbsp;</td>
                <td bgcolor="#FFECEC">&nbsp;</td>
                <td bgcolor="#FFECEC">
                    <input type="text" name="startdate" id="startdate" style="width:164px" value="<?php echo $this->experienceRowSet->getStartDate();?>">
                    <span class="subtitle_popup" style="padding-left:20px">End date:<span class="error">*</span></span> 
                    <input type="text" name="enddate" id="enddate" style="width:163px" value="<?php echo $this->experienceRowSet->getEndDate();?>">
                </td>
            </tr>
            <tr>
                <td class="subtitle_popup">Job Title:<span class="error">*</span></td>
                <td>&nbsp;</td>
                <td bgcolor="#FFECEC">&nbsp;</td>
                <td colspan="2" bgcolor="#FFECEC">
                	<input type="text" name="job_title" id="job_title" style="width: 415px" value="<?php echo $this->experienceRowSet->getJobTitle();?>"/>
                </td>
            </tr>
            <tr>
                <td class="subtitle_popup">Company:<span class="error">*</span></td>
                <td>&nbsp;</td>
                <td bgcolor="#FFECEC">&nbsp;</td>
                <td height="30" colspan="2" bgcolor="#FFECEC">
                	<input type="text" name="company_name" id="company_name" style="width:415px" value="<?php echo $this->experienceRowSet->getCompanyName();?>"/>
                </td>
            </tr>
            <tr>
                <td class="subtitle_popup">Function:</td>
                <td>&nbsp;</td>
                <td bgcolor="#FFECEC">&nbsp;</td>
                <td height="30" colspan="2" bgcolor="#FFECEC">
                	<input type="text" name="function" id="function" style="width:415px" value=""/>
                	<div class="multiselect" style="width:800px; height:250px; padding:10px;display:none; position:fixed">
                    	<div style="width: 33%; float: left">
                            <ul style="list-style-type:none;">
                            <?php 
                            $i = 1;
                            $checked = '';
                            foreach($this->listFunction as $function) :
                                if($i % 44 == 0): echo '</ul></div><div style="width: 33%; float: left"><ul style="list-style-type:none;">';endif;
                                if($function['parent_function_id'] == 0) echo '<div><strong>'. $function['name'] .'</strong></div>';
                                if(in_array($function['function_id'], $this->experFunction, true)) $checked = "checked";
                                else $checked = '';
                            ?>
                                <li><input type="checkbox" name="option[]" value="<?php echo $function['function_id']?>" <?php echo $checked;?>/> <?php echo $function['name']?></li>
                                    
                            <?php 
                            $i++;
                            endforeach;?>
                            </ul>
                    	</div>
                        <div style="clear: both">&nbsp;</div>
               		</div>
                </td>
            </tr>
            <tr>
                <td valign="top" class="subtitle_popup">Info:</td>
                <td>&nbsp;</td>
                <td bgcolor="#FFECEC">&nbsp;</td>
                <td height="30" colspan="2" bgcolor="#FFECEC">
                	<textarea name="info" id="info" style="height:200px; width:500px"><?php echo $this->experienceRowSet->getInfo();?></textarea></td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td colspan="3" align="center">
                	<input type="hidden" name="resume_id" value="<?php echo $this->resumeId; ?>" />
                	<input type="hidden" name="experid" value="<?php echo $this->experienceRowSet->getId();?>" />
                	<a href="/resume/personal-info/id/<?php echo $this->resumeId; ?>"><input type="button" name="button" value="Back"/></a>
                	<input type="submit" name="button" value="Save"/>
                	<a href="/resume/expectation/id/<?php echo $this->resumeId; ?>"><input type="button" name="button" value="Next"/></a>
                </td>
            </tr>
        </table>
        </td>
        <td>&nbsp;</td>
        <td width="48%" valign="top">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td colspan="2"><strong>Resume Preview</strong></td>
            </tr>
            <tr>
                <td colspan="2">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="2" bgcolor="#999999" style="font-size: 15px; padding: 5px 5px; color: #FFFFFF">
                    <strong>CAREER SUMMARY</strong>
                </td>
            </tr>
            <tr>
                <td height="15" colspan="2"></td>
            </tr>
            <?php foreach($this->rows as $row) : 
                $date = date_create($row->getStartDate());
                $startDate = date_format($date, 'M Y');
                
                $date = date_create($row->getEndDate());
                $endDate = date_format($date, 'M Y');
            ?>
            <tr>
                <td valign="top" width="125"><?php echo $startDate;?> - <?php echo $endDate; ?><br />
                    <span class="a-left"><a href="/resume/experience/id/<?php echo $this->resumeId; ?>/experid/<?php echo $row->getId();?>">Edit</a></span> |
                    <span class="a-left"><a href="/resume/del-experience/id/<?php echo $this->resumeId; ?>/experid/<?php echo $row->getId();?>">Delete</a></span>
                </td>
                <td align="left">
                    <strong><?php echo $row->getCompanyName();?></strong><br />
                    <?php echo $row->getJobTitle();?>
                </td>
            </tr>
            <?php endforeach;?>
        </table>
        </td>
    </tr>
</table>
</form>
<script>
$(function() {
    $( "#startdate" ).datepicker({
		changeMonth: true,
		changeYear: true
	});
    $( "#enddate" ).datepicker({
		changeMonth: true,
		changeYear: true
	});
});

function checkValid()
{
	var startdate = $("#startdate").val();
	var enddate = $("#enddate").val();
	var job_title = $("#job_title").val();
	var company_name = $("#company_name").val();
    
    if(startdate == '' || enddate == '' || job_title == '' || company_name == '') {
        $('#error').html('Please input into field required (*)');
        return false;
    }
    return true;
}   
</script>
<script>
$(document).ready(function(){
    $("#function").click(function(){
        if(($(".multiselect").css('display')) == 'none') $(".multiselect").show('slow');
        else $(".multiselect").hide('slow');
    });
});

$('.multiselect').mouseleave(function(){
	$(".multiselect").hide('slow');
});

jQuery.fn.multiselect = function() {
    $(this).each(function() {
        var checkboxes = $(this).find("input:checkbox");
        checkboxes.each(function() {
            var checkbox = $(this);
           
        });
    });
};

$(".multiselect").multiselect();
</script>