<?php $aNamespace = new Zend_Session_Namespace ( 'zs_User' ); ?>
<div style="width:550px;height: 230px; display:none" id="history">
	<form name="frmcomment" method="post" action="/resume/save-comment">
		<div style="color:#1B7CBD;background-color:#CCC;padding:5px 0px"><b>ADD HISTORY</b></div><br />
		<label>Content</label> &nbsp;&nbsp;<span id="msghistory" class="error"></span><br />
		<textarea name="content" id="contenthistory" style="width:500px;height:100px"></textarea><br /><br />
		<input type="hidden" name="resume_id" value="">
		<input type="hidden" name="consultant_id" value="<?php echo $aNamespace->consultant_id;?>">
		<div class="actions">
			<input type="button" class="button01" name="add" id="inserthistory" value="Add">
			<input type="button" class="button02" name="cancel" value="Cancel" onclick="event.preventDefault(); parent.$.fancybox.close();">
		</div>
	</form>
</div>