<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
	  <td><form id="form" action="../..." method="post">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
		  <tr>
			<td width="5%"><label for="choice">Search : </label></td>
			<td width="6%"><select name="choice">
				<option>Name</option>
			</select></td>
			<td width="13%"><input name="text" id="textbox" type="text"/></td>
			<td width="5%"><input id="button1" type="submit" value="Search" /></td>
			<td width="8%"><input id="button8" type="submit" value="Advanced Search" /></td>
			<td width="8%" align="left"><input id="button11" type="submit" value="Refine Search" /></td>
			<td width="7%" align="left"><input id="button12" type="submit" value="My Shortlists" /></td>
			<td width="48%" align="right">&nbsp;</td>
		  </tr>
		</table>
	  </form></td>
	</tr>
	
	<tr>
	  <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
		<tr>
		  <td width="7%"><input id="button4" type="submit" value="Add Resume" class="link_button" /></td>
		  <td width="5%"><input id="button5" type="submit" value="Add Short List" class="link_button" /></td>
		  <td width="35%"><em>Showing 30 of 50 records</em></td>
		  <td width="15%" align="right"><strong>View:</strong> <a href="view_detail.html">Detail</a> | <a href="brief_view.html">Brief</a></td>
		  <td width="5%" align="right">&nbsp;</td>
		  <td width="30%" align="right">Today Entry: <strong>New 18</strong> | Updated: <strong>20</strong> | Total: <strong>120000</strong></td>
		</tr>
	  </table></td>
	</tr>
  </table>
  <div id="box">
	<table width="100%" class="datagrid">
	  <thead>
		<tr>
		  <th width="26"><input type="checkbox" name="checkbox" id="checkbox" /></th>
		  <th class="a-left">&nbsp;</th>
		</tr>
	  </thead>
	  <tbody>
		<tr>
		  <td valign="top" class="a-center"><input type="checkbox" name="checkbox5" id="checkbox5" /></td>
		  <td class="a-left"><table width="100%" border="0" cellspacing="0" cellpadding="0" class="noboder">
			<tr>
			  <td width="154" valign="top"><a href="#"><strong>Tran Thanh Son</strong></a><br />
R119905</td>
			  <td width="470" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0" class="noboder01">
				<tr>
				  <td width="83" valign="top">2004 -</td>
				  <td width="381" valign="top"><strong class="text_green">BASF CONSTRUCTION CHEMICAL COMPANY</strong><br />
Sales Supervisor - Infrastructure, RMC, and Mega Project</td>
				</tr>
				<tr>
				  <td valign="top">2007 - 2009</td>
				  <td valign="top"><strong class="text_green">MASAN FOOD JOINT – STOCK COMPANY</strong><br />
Market Researcher</td>
				</tr>
				<tr>
				  <td valign="top">2007 - 2008</td>
				  <td valign="top"><strong class="text_green">HOANG KHOA CONSULTANT AND TRAINING COMPANY</strong><br />
Market Researcher <a href="#">&nbsp;&nbsp;&nbsp;view more</a></td>
				</tr>
			  </table></td>
			  <td width="282" valign="top"><strong class="text_blue">FOREIGN TRADE UNIVERSITY OF HCMC</strong><br />
Bachelor of Foreign language
<p>&nbsp;</p>
[S]: $1,000<br />
[E]: $1 500-$2 000<br />
[L]: HCMC, Binh Duong
<p>&nbsp;</p>
Upd: 14-Apr-11 Views: 124 Sent: 7 Email:</td>
			  <td width="286" valign="top" class="color_bg"><img src="../img/icons/add.png" width="16" height="16" /><img src="../img/icons/application_add.png" width="16" height="16" /><img src="../img/icons/add.png" width="16" height="16" /><img src="../img/icons/application_add.png" width="16" height="16" /> 
			  <p>&nbsp;</p>
			  <strong class="text_green">Sent Feb-11</strong> <strong>by HoanN</strong>: <br />                      <img src="../img/process_orange_90.gif" width="100" height="10" /> <br />
				  Unilever Vietnam Ltd<br />
				  Business Development Manager
				<p>&nbsp;</p>
				<strong class="text_green">Comment Jan-10</strong> <strong>by MaiB:</strong><br />
Lorem ipsum dolor sit amet,<br />
consectetur adipisicing elit…. <a href="#">view</a></td>
			</tr>
		  </table></td>
		</tr>
		<tr>
		  <td valign="top" class="a-center"><input type="checkbox" name="checkbox6" id="checkbox6" /></td>
		  <td class="a-left"><table width="100%" border="0" cellspacing="0" cellpadding="0" class="noboder">
			<tr>
			  <td width="154" valign="top"><a href="#"><strong>Tran Thanh Son</strong></a><br />
				R119905</td>
			  <td width="470" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0" class="noboder01">
				  <tr>
					<td width="83" valign="top">2004 -</td>
					<td width="381" valign="top"><strong class="text_green">BASF CONSTRUCTION CHEMICAL COMPANY</strong><br />
					  Sales Supervisor - Infrastructure, RMC, and Mega Project</td>
				  </tr>
				  <tr>
					<td valign="top">2007 - 2009</td>
					<td valign="top"><strong class="text_green">MASAN FOOD JOINT – STOCK COMPANY</strong><br />
					  Market Researcher</td>
				  </tr>
				  <tr>
					<td valign="top">2007 - 2008</td>
					<td valign="top"><strong class="text_green">HOANG KHOA CONSULTANT AND TRAINING COMPANY</strong><br />
					  Market Researcher <a href="#">&nbsp;&nbsp;&nbsp;view more</a></td>
				  </tr>
			  </table></td>
			  <td width="282" valign="top"><strong class="text_blue">FOREIGN TRADE UNIVERSITY OF HCMC</strong><br />
				Bachelor of Foreign language
				<p>&nbsp;</p>
				[S]: $1,000<br />
				[E]: $1 500-$2 000<br />
				[L]: HCMC, Binh Duong
				<p>&nbsp;</p>
				Upd: 14-Apr-11 Views: 124 Sent: 7 Email:</td>
			  <td width="286" valign="top" class="color_bg"><img src="../img/icons/add.png" width="16" height="16" /><img src="../img/icons/application_add.png" width="16" height="16" /><img src="../img/icons/add.png" width="16" height="16" /><img src="../img/icons/application_add.png" width="16" height="16" />
				  <p>&nbsp;</p>
				<strong class="text_green">Sent Feb-11</strong> <strong>by HoanN</strong>: <br />
				  <img src="../img/process_orange_90.gif" width="100" height="10" /> <br />
				Unilever Vietnam Ltd<br />
				Business Development Manager
				<p>&nbsp;</p>
				<strong class="text_green">Comment Jan-10</strong> <strong>by MaiB:</strong><br />
				Lorem ipsum dolor sit amet,<br />
				consectetur adipisicing elit…. <a href="#">view</a></td>
			</tr>
		  </table></td>
		</tr>
		<tr>
		  <td valign="top" class="a-center"><input type="checkbox" name="checkbox7" id="checkbox7" /></td>
		  <td class="a-left"><table width="100%" border="0" cellspacing="0" cellpadding="0" class="noboder">
			<tr>
			  <td width="154" valign="top"><a href="#"><strong>Tran Thanh Son</strong></a><br />
				R119905</td>
			  <td width="470" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0" class="noboder01">
				  <tr>
					<td width="83" valign="top">2004 -</td>
					<td width="381" valign="top"><strong class="text_green">BASF CONSTRUCTION CHEMICAL COMPANY</strong><br />
					  Sales Supervisor - Infrastructure, RMC, and Mega Project</td>
				  </tr>
				  <tr>
					<td valign="top">2007 - 2009</td>
					<td valign="top"><strong class="text_green">MASAN FOOD JOINT – STOCK COMPANY</strong><br />
					  Market Researcher</td>
				  </tr>
				  <tr>
					<td valign="top">2007 - 2008</td>
					<td valign="top"><strong class="text_green">HOANG KHOA CONSULTANT AND TRAINING COMPANY</strong><br />
					  Market Researcher <a href="#">&nbsp;&nbsp;&nbsp;view more</a></td>
				  </tr>
			  </table></td>
			  <td width="282" valign="top"><strong class="text_blue">FOREIGN TRADE UNIVERSITY OF HCMC</strong><br />
				Bachelor of Foreign language
				<p>&nbsp;</p>
				[S]: $1,000<br />
				[E]: $1 500-$2 000<br />
				[L]: HCMC, Binh Duong
				<p>&nbsp;</p>
				Upd: 14-Apr-11 Views: 124 Sent: 7 Email:</td>
			  <td width="286" valign="top" class="color_bg"><img src="../img/icons/add.png" width="16" height="16" /><img src="../img/icons/application_add.png" width="16" height="16" /><img src="../img/icons/add.png" width="16" height="16" /><img src="../img/icons/application_add.png" width="16" height="16" />
				  <p>&nbsp;</p>
				<strong class="text_green">Sent Feb-11</strong> <strong>by HoanN</strong>: <br />
				  <img src="../img/process_orange_90.gif" width="100" height="10" /> <br />
				Unilever Vietnam Ltd<br />
				Business Development Manager
				<p>&nbsp;</p>
				<strong class="text_green">Comment Jan-10</strong> <strong>by MaiB:</strong><br />
				Lorem ipsum dolor sit amet,<br />
				consectetur adipisicing elit…. <a href="#">view</a></td>
			</tr>
		  </table></td>
		</tr>
	  </tbody>
	</table>
  </div>
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
	  <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
		<tr>
		  <td width="7%"><input id="button2" type="submit" value="Add Resume" class="link_button" /></td>
		  <td width="5%"><input id="button3" type="submit" value="Add Shortlist" class="link_button" /></td>
		  <td width="84%">&nbsp;</td>
		</tr>
	  </table></td>
	</tr>
	
	<tr>
	  <td>            <table width="100%" border="0" cellspacing="0" cellpadding="0">
		  <tr>
			<td width="5%"><label for="choice">Showing</label></td>
			<td width="4%"><select name="choice6">
				<option>30</option>
			</select></td>
			<td width="91%">records per page</td>
		  </tr>
	  </table></td>
	</tr>
	
	<tr>
	  <td align="center">Back&nbsp;&nbsp;|&nbsp;&nbsp;1&nbsp;&nbsp;|&nbsp;&nbsp;2&nbsp;&nbsp;|&nbsp;&nbsp;3&nbsp;&nbsp;|&nbsp;&nbsp;4&nbsp;&nbsp;|&nbsp;&nbsp;5&nbsp;&nbsp;|&nbsp;&nbsp;Next</td>
	</tr>
  </table>