<!-- Add fancyBox main JS and CSS files -->
<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td>
        <form id="form" action="/resume" method="post">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td width="5%"><label for="choice">Search : </label></td>
                <td width="9%">
                    <select name="choice" style="width:110px"> 
                        <option value="full_name">Name</option>
                        <option value="resume_code">Resume Code</option>
                        <option value="job_title">Job Title</option>
                    </select>
                </td>
                <td width="13%">
                    <input name="search" id="textbox" type="text" />
                </td>
                <td width="5%">
                    <input id="button1" type="submit" value="Search" />
                </td>
                <td width="8%">
                    <a href="#inline" class="fancybox">
                    <input type="button" value="Advanced Search" />
                    </a>
                </td>
                <td width="*%" align="right">&nbsp;</td>
            </tr>
        </table>
        </form>
        </td>
    </tr>

    <tr>
        <td>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td width="7%"><a href="/resume/personal-info">
                    <input id="button4" type="button" value="Add Resume" class="link_button" /></a>
                </td>
                <td width="35%"></td>

                <td width="5%" align="right">&nbsp;</td>
                <td width="30%" align="right">
                    <div id="report"></div>
                </td>
            </tr>
        </table>
        </td>
    </tr>
</table>
<div id="box">
    <?php echo $this->partial ( '/resume/list-resume.phtml', array('rows' => $this->rows, 'paginator' => $this->paginator) )?>
</div>
<?php echo $this->partial ( '/resume/avandced-search.phtml' )?>
<script type="text/javascript">
$(document).ready(function() {
    $(".fancybox").fancybox();

    $("#avansearch").click(function(){
        var name = $('#full_name').val();
        var email = $('#email').val();
        var phone = $('#phone').val();
        var gender = $('input[name=gender]:radio:checked').val();
        var marital_status = $('input[name=marital_status]:radio:checked').val();
        
        $.ajax({
      	  	url: '/resume/avandce-search',
        	type: "POST",
			data: { 
                full_name: name, 
                email: email, 
                phone: phone, 
                gender: gender, 
                marital_status: marital_status
            },
      	  	success: function(result) {
      	    	$('#box').html(result);
        	  	$.fancybox.close();
      	  	}
      	});
    });

    $.ajax({
  	  	url: '/resume/resume-report',
  	  	success: function(result) {
  	    	$('#report').html(result);
  	  	}
  	});
});
</script>