<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<?php echo $this->partial('resume/menu-add-resume.phtml')?>
<form name="frm" method="post" action="save-resume" onsubmit="return checkValid()">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
        <td width="15%"></td>
        <td id="error" class="error"></td>
    </tr>
    <tr>
		<td width="15%">Full Name:<span class=error>*</span></td>
		<td> <input type="text" name="full_name" id="full_name" style="width: 225px" /></td>
	</tr>
	<tr>
		<td>Birthday:<span class=error>*</span></td>
		<td><input type="text" name="birthday" id="birthday" style="width: 225px" /></td>
	</tr>		
	<tr>
		<td>Gender:<span class="error">*</span></td>
		<td>
			<input type="radio"	name="gender" value="Male" /> Male &nbsp;&nbsp;&nbsp; 
			<input type="radio" name="gender" value="Female" /> Female
		</td>
	</tr>
	<tr>
		<td>Marital Status:</td>
		<td>
			<input type="radio"	name="marital_status" value="Single" /> Single &nbsp;&nbsp;&nbsp;
			<input type="radio" name="marital_status" value="Married" /> Married &nbsp;&nbsp;&nbsp; 
			<input type="radio" name="marital_status" value="Divorced" /> Divorced
		</td>
	</tr>
	<tr>
		<td>Email1:<span class="error">*</span></td>
		<td><input type="text" name="email_1" id="email_1"  style="width:225px" /></td>
	</tr>
	<tr>
		<td>Email2:</td>
		<td><input type="text" name="email_2"  style="width:225px" /></td>
	</tr>
	<tr>
		<td>Mobile1:<span class="error">*</span></td>
		<td><input type="text" name="mobile_1" id="mobile_1" style="width:225px" /></td>
	</tr>
	<tr>
		<td>Mobile2:</td>
		<td><input type="text" name="mobile_2"  style="width:225px" /></td>
	</tr>
	<tr>
		<td>Telephone:</td>
		<td><input type="text" name="tel" style="width:225px" /></td>
	</tr>
	<tr>
		<td>Address:<span class="error">*</span></td>
		<td><input type="text" name="address" id="address" style="width:225px" /></td>
	</tr>
	<tr>	
		<td>&nbsp;</td>
		<td>
			<input type="button" name="cancel" value="Cancel" /> &nbsp;&nbsp; 
			<input type="submit" name="next" value="Next &gt;&gt;" />
		</td>
	</tr>
</table>
</form>
<script>
$(function() {
    $( "#birthday" ).datepicker();
});

function checkValid()
{
    var fullname = $("#full_name").val();
    var birthday = $("#birthday").val();
    var email1 = $("#email_1").val();
    var mobile1 = $("#mobile_1").val();
    var address = $("#address").val();
    
    if(fullname == '' || birthday == '' || email1 == '' || mobile1 == '' || address == '') {
        $('#error').html('Please input into field required (*)');
        return false;
    }
    return true;
}   
</script>