<?php 
$resume = new Default_Model_ExperienceMapper();
$listFunction = $resume->getFunction();
?>
<div style="width:900px;height: 450px; display: none;" id="inline">
<div id="adv-search" class="content">
<form name="frmAvanSearch" id="frmAvanSearch" method="post" action="/resume/avandce-search" >
	<h2>Search Personal Details</h2>
	<ul>
		<li>
			<label>Candidate Name</label>
			<input type="text" name="full_name" id="full_name" value="" />
		</li>
		<li>
			<label>Email</label>
			<input type="text" name="email" id="email" value="" />
		</li>                    
		<li>
			<label>Phone</label>
			<input type="text" name="phone" id="phone" value="" />
		</li>
		<li>
			<label>Gender</label>
			<input type="radio" name="gender" value="female" /> <span>Female</span>
			<input type="radio" name="gender" value="male" /> <span>Male</span>
		</li>
		<li>
			<label>Marital Status</label>
			<input type="radio" name="marital_status" value="single" /> <span>Single</span>
			<input type="radio" name="marital_status" value="mrried" /> <span>Married</span>
			<input type="radio" name="marital_status" value="divorced" /> <span>Divorced</span>
		</li>

	</ul>

	<h2>SEARCH EXPERIENCE, SALARY, WORK LOCATION</h2>
	<ul>
		<li>
			<label>Job Title</label>
			<input type="text" name="job_title" id="job_title" value="" />
		</li>
		<li>
			<label>Salary</label>
			<select name="symbol" id="symbol" style="width: 60px">
				<option value="1">=</option>
				<option value="2"> &gt; </option>
				<option value="3"> &lt; </option>
			</select> 
			<input class="cost" type="text" name="salary" id="salary" value="" /> <span style="float:none !important; ">USD</span>
		</li>
		<li>
			<label>Company</label>
			<input type="text" name="company_name" id="company_name" value="" />
		</li>                    
		<li>
			<label>Info</label>
			<input type="text" name="info" id="info" value="" />
		</li>
		<li>
			<label>Function</label>
			<input type="text" name="function" id="function" value=""/>
			<div class="multiselect" style="width:800px; height:250px; padding:10px;display:none; position:absolute">
				<div style="width: 33%; float: left">
					<ul style="list-style-type:none;margin: 10px 0;">
					<?php 
					$i = 1;
					$checked = '';
					foreach($listFunction as $function) :
						if($i % 46 == 0): echo '</ul></div><div style="width: 33%; float: left"><ul style="list-style-type:none;margin: 10px 0;">';endif;
						if($function['parent_function_id'] == 0) echo '<div><strong>'. $function['name'] .'</strong></div>';
						//if(in_array($function['function_id'], $this->experFunction, true)) $checked = "checked";
						//else $checked = '';
					?>
						<li style="float:none;display:block;"><input type="checkbox" name="option[]" value="<?php echo $function['function_id']?>" <?php echo $checked;?>/>&nbsp; <?php echo $function['name']?></li>
							
					<?php 
					$i++;
					endforeach;?>
					</ul>
				</div>
				<div style="clear: both">&nbsp;</div>
			</div>
		</li>
		<li>
			<label>&nbsp;</label>
			<input type="checkbox" value="" /> <p>Search last experience only</p>
		</li>
	</ul>
	<div class="actions">
		<input type="button" class="button02" name="cancel" id="cancel" value="Cancel"  onclick="event.preventDefault(); parent.$.fancybox.close();">
		<input type="button" class="button01" name="avansearch" id="avansearch" value="Search">
	</div>
</form>
</div>
</div>