<?php 
$resume = new Default_Model_ExperienceMapper();
$listFunction = $resume->getFunction();
?>
<table border="2" cellpadding="0" cellspacing="0" bordercolor="#CCCCCC" style="border-collapse:collapse">
  <tr>
    <td valign="top" style="padding:15px 15px 15px 15px"><table width="100%" border="0" cellspacing="0" cellpadding="0">
        
        <tr>
          <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td colspan="3" bgcolor="#990000" class="title_popup"><img src="/images/icons/icon_expand.gif" width="9" height="9" />PERSONAL DETAILS</td>
              </tr>
              <tr>
                <td height="20" colspan="3"></td>
              </tr>
              <tr>
                <td width="45%" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td width="10%" align="right"></td>
                      <td width="4%"></td>
                      <td colspan="2" bgcolor="#FFECEC"></td>
                    </tr>
                    <tr>
                      <td class="subtitle_popup">Candidate Name:</td>
                      <td>&nbsp;</td>
                      <td width="5%" bgcolor="#FFECEC">&nbsp;</td>
                      <td width="63%" bgcolor="#FFECEC"><?php echo $this->resume->getFullName();?></td>
                    </tr>
                    <tr>
                      <td class="subtitle_popup">Birthday:</td>
                      <td>&nbsp;</td>
                      <td bgcolor="#FFECEC">&nbsp;</td>
                      <td bgcolor="#FFECEC"><?php echo $this->resume->getBirthday();?></td>
                    </tr>
                    <tr>
                      <td class="subtitle_popup">Gender:</td>
                      <td>&nbsp;</td>
                      <td width="4%" bgcolor="#FFECEC">&nbsp;</td>
                      <td width="67%" bgcolor="#FFECEC"><?php echo $this->resume->getGender();?></td>
                    </tr>
                     <tr>
                      <td valign="top" class="subtitle_popup">Marital Status:</td>
                      <td>&nbsp;</td>
                      <td bgcolor="#FFECEC">&nbsp;</td>
                      <td bgcolor="#FFECEC"><?php echo $this->resume->getMaritalStatus();?></td>
                    </tr>
                    <tr>
                      <td valign="top" class="subtitle_popup">Address:</td>
                      <td>&nbsp;</td>
                      <td bgcolor="#FFECEC">&nbsp;</td>
                      <td bgcolor="#FFECEC"><?php echo $this->resume->getAddress();?></td>
                    </tr>
                    <tr>
                      <td class="subtitle_popup">Email:</td>
                      <td>&nbsp;</td>
                      <td bgcolor="#FFECEC">&nbsp;</td>
                      <td bgcolor="#FFECEC"><?php echo $this->resume->getEmail1();?></td>
                    </tr>
                    <tr>
                      <td class="subtitle_popup">Phone:</td>
                      <td>&nbsp;</td>
                      <td bgcolor="#FFECEC">&nbsp;</td>
                      <td bgcolor="#FFECEC"><?php echo $this->resume->getMobile1();?></td>
                    </tr>
                    <tr>
                      <td></td>
                      <td></td>
                      <td colspan="2" bgcolor="#FFECEC"></td>
                    </tr>
                  </table></td>
              </tr>
            </table></td>
        </tr>
        <tr>
          <td height="20"></td>
        </tr>
        <tr>
          <td>
          <?php 
            
            
            
            $experienceMapper = new Default_Model_ExperienceMapper();
            $experienceList = $experienceMapper->fetchAll('resume_id = ' . $this->resume->getResumeId(), 'end_date DESC');
            
            $resumeMapper = new Default_Model_ResumeMapper();
            $comment = $resumeMapper->getComments($this->resume->getResumeId(), 1);
            $date = new DateTime($comment['created_date']);
            $createdComment = $date->format('M-d');
            
            ?>
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td colspan="3" bgcolor="#990000" class="title_popup"><img src="/images/icons/icon_expand.gif" width="9" height="9" />CAREER SUMMARY</td>
            </tr>
            <tr>
              <td height="20" colspan="3"></td>
            </tr>
            <tr>
              <td width="45%" valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="0" class="noboder01">
                        <?php foreach ( $experienceList as $experience ) :
                            $date = new DateTime($experience->getStartDate());
                            $startDate = $date->format('M Y');
                
                            $date = new DateTime($experience->getEndDate());
                            $endDate = $date->format('M Y');
                        ?>
                        <tr>
                            <td width="115" valign="top">
                                <?php echo $startDate;?> - <?php echo $endDate;?> 
                            </td>
                            <td width="376" valign="top">
                                <strong class="text_green"><?php echo $experience->getCompanyName();?></strong>
                                <br /> <?php echo $experience->getJobTitle();?>
                            </td>
                        </tr>
                        <?php endforeach;?>

                    </table>
                </td>
            </tr>
            <tr>
                <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td colspan="3" bgcolor="#990000" class="title_popup"><img src="/images/icons/icon_expand.gif" width="9" height="9" />EXPECTION</td>
            </tr>
            <tr>
              <td height="20" colspan="3"></td>
            </tr>
            <tr><td height="20" colspan="3">
                    <?php 
                    $expectationMapper = new Default_Model_ExpectationMapper();
                    $expectation = $expectationMapper->getExpectation($this->resume->getResumeId());
                    
                    $provinceArr = array();
                    if($expectation['res_expectation_id']) {
                        $resumeProvince = $expectationMapper->getExpectationProvince($expectation['res_expectation_id']);
                        foreach($resumeProvince as $province){
                            $provinceArr[] = $province['name'];
                        }
                    }
        
                    $currentSalary = number_format($expectation['current_salary']);
                    @$salaryFrom = number_format($expectation['estimated_salary_from']);
                    @$salaryTo = number_format($expectation['estimated_salary_to']);
                    ?>
                    Salary: <?php if($currentSalary) echo '$'.$currentSalary; ?><br />
                    Estimated: <?php if($salaryFrom) echo '$'.$salaryFrom; ?><?php if($salaryTo) echo ' - '.'$'.$salaryTo; ?><br />
                    Location: <?php echo implode(', ', $provinceArr);?>
             </td>
             </tr></table></td>
              <td width="2%">&nbsp;</td>
             
            </tr>
          </table></td>
        </tr>
        <tr>
          <td height="20"></td>
        </tr>
       
        <tr>
          <td><hr /></td>
        </tr>
        <tr>
          <td align="center">
              <a href="/resume/export-to-word/id/<?php echo $this->resume->getResumeId();?>"><input type="button" name="export" value="Export to Word"></a>&nbsp;&nbsp;&nbsp;
              <a href="/resume/personal-info/id/<?php echo $this->resume->getResumeId();?>"><input type="button" name="edit" value="Edit"></a>&nbsp;&nbsp;&nbsp;
              <input type="button" name="cancel" value="Cancel" onclick="$.fancybox.close();"/>
          </td>
        </tr>
    </table></td>
  </tr>
  <tr></tr>
</table>

