<?php echo $this->partial('resume/menu-add-resume.phtml')?>
<form name="frm" method="post" action="">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="50%" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td width="17%" align="right"></td>
                  <td width="4%"></td>
                  <td colspan="3" bgcolor="#FFECEC"></td>
                </tr>
                <tr>
                  <td class="subtitle_popup">Period:</td>
                  <td>&nbsp;</td>
                  <td width="5%" bgcolor="#FFECEC">&nbsp;</td>
                  <td colspan="2" bgcolor="#FFECEC"><input name="textfield2" type="text" id="textfield2" style="width:60px" value="MM" />
                    &nbsp;&nbsp;<input name="textfield5" type="text" id="textfield5" style="width:60px" value="YY" /> 
                    &nbsp;&nbsp;- &nbsp;&nbsp;
                    <input name="textfield6" type="text" id="textfield6" style="width:60px" value="MM" />
                    &nbsp;&nbsp;
                    <input name="textfield7" type="text" id="textfield7" style="width:60px" value="YY" /></td>
                </tr>
                <tr>
                  <td class="subtitle_popup">Job Title:</td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td colspan="2" bgcolor="#FFECEC"><input type="text" name="textfield" id="textfield" style="width:415px" /></td>
                </tr>
                <tr>
                  <td class="subtitle_popup">Company:</td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td height="30" colspan="2" bgcolor="#FFECEC"><input type="text" name="textfield3" id="textfield3" style="width:415px" /></td>
                </tr>
                <tr>
                  <td valign="top" class="subtitle_popup">Company Info:</td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td height="30" colspan="2" bgcolor="#FFECEC"><textarea name="textfield4" id="textfield4" style="height:80px"></textarea></td>
                </tr>
                <tr>
                  <td valign="top" class="subtitle_popup">Work Location:</td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td width="29%" height="30" valign="top" bgcolor="#FFECEC"><p><strong>Country:</strong></p>                    </td>
                  <td width="45%" height="30" bgcolor="#FFECEC"><strong>Province/ City:</strong></td>
                </tr>
                <tr>
                  <td valign="top" class="subtitle_popup">&nbsp;</td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td height="30" bgcolor="#FFECEC"><select name="choice" style="width:80px">
  <option></option>
</select></td>
                  <td height="30" valign="top" bgcolor="#FFECEC"><select name="choice2" style="width:80px">
                    <option></option>
</select></td>
                </tr>
                
                <tr>
                  <td valign="top" class="subtitle_popup">Duties:</td>
                  <td valign="top">&nbsp;</td>
                  <td valign="top" bgcolor="#FFECEC">&nbsp;</td>
                  <td colspan="2" valign="top" bgcolor="#FFECEC"><textarea name="textfield8" id="textfield8" style="height:150px"></textarea></td>
                  </tr>
                
                <tr>
                  <td></td>
                  <td></td>
                  <td colspan="3" bgcolor="#FFECEC"></td>
                </tr>
                <tr>
                  <td>&nbsp;</td>
                  <td>&nbsp;</td>
                  <td colspan="3" align="center" bgcolor="#FFECEC"><input type="submit" name="button2" id="button2" value="Add Experience &gt;&gt;" /></td>
                </tr>
                <tr>
                  <td></td>
                  <td></td>
                  <td colspan="3" bgcolor="#FFECEC"></td>
                </tr>
                <tr>
                  <td colspan="5"></td>
                  </tr>
                <tr>
                  <td>&nbsp;</td>
                  <td>&nbsp;</td>
                  <td colspan="3" align="center"><input type="submit" name="button" id="button" value="&lt;&lt; Back" /> 
                    &nbsp;&nbsp;
                    <input type="submit" name="button3" id="button14" value="Close" />                    &nbsp;&nbsp;
                    <input type="submit" name="button6" id="button16" value="Next &gt;&gt;" /></td>
                </tr>
            </table></td>
            <td>&nbsp;</td>
            <td width="48%" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td colspan="2"><strong>Resume Preview</strong></td>
              </tr>
              <tr>
                <td colspan="2">&nbsp;</td>
              </tr>
              <tr>
                <td colspan="2" bgcolor="#999999" style="font-size:15px; padding:5px 5px; color:#FFFFFF"><strong>CAREER SUMMARY</strong></td>
              </tr>
              <tr>
                <td height="15" colspan="2"></td>
              </tr>
              <tr>
                <td width="26%" valign="top" >Oct 2010 - Present<br />
                  <span class="a-left"><img src="../img/icons/user_edit.png" width="16" height="16" /><img src="../img/icons/user.png" width="16" height="16" /><img src="../img/icons/user_add.png" width="16" height="16" /> <img src="../img/icons/user_delete.png" width="16" height="16" /></span></td>
                <td width="74%" ><strong>CHEVRON LUBRICANTS VIETNAM LTD (CLVL)</strong><br />
                  Contact Center Director</td>
              </tr>
              <tr>
                <td valign="top" >Nov 2006 - Oct 2010<br />
                  <span class="a-left"><img src="../img/icons/user_edit.png" width="16" height="16" /><img src="../img/icons/user.png" width="16" height="16" /><img src="../img/icons/user_add.png" width="16" height="16" /> <img src="../img/icons/user_delete.png" width="16" height="16" /></span></td>
                <td ><strong>AUSTRALIAN &amp; VIETNAMESE JOINT VENTURE INTERIORS COMPANY</strong><br />
                  Call Center Manager</td>
              </tr>
              <tr>
                <td height="15" colspan="2"></td>
              </tr>
              <tr>
                <td colspan="2" bgcolor="#999999" style="font-size:15px; padding:5px 5px; color:#FFFFFF"><strong>PROFESSIONAL EXPERIENCE</strong></td>
              </tr>
              <tr>
                <td height="15" colspan="2"></td>
              </tr>
              <tr>
                <td width="26%" valign="top" >Oct 2010 - Present</td>
                <td width="74%" ><strong>CHEVRON LUBRICANTS VIETNAM LTD (CLVL)</strong><br />
                  Business Planning and Demand Manager
                    <em><br />
                    <br />
                    Work Location: HCMC</em><br />
                    <br />                    
                    <strong>Duties:</strong>                    <br />
                    <br />
                    Aug 2007- Present: Business Planning and Demand Manager<br />
                    Strategic and Business Plan Development:<br />
                    • Coordinate with all functions of the company to compose and<br />
                    lead the Business Planning Process with a view to develop 3-<br />
                    year strategic plan for the company’s which is aligned with<br />
                    Regional/ Global objectives.<br />
                    • Develop the business target &amp; allocate trade fund for sales &amp;<br />
                    marketing teams of the company; monitor their progress against<br />
                    objectives; identify variations versus budgets, develop<br />
                    appropriate plans together with sales &amp; marketing managers to<br />
                    address variations and support their executions.</td>
              </tr>
              <tr>
                <td height="15" colspan="2"></td>
              </tr>
            </table></td>
          </tr>
        </table> </form>
</form>