<!-- Add fancyBox main JS and CSS files -->
<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td>
        <form id="form" action="/resume" method="post">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td width="5%"><label for="choice">Search : </label></td>
                <td width="9%">
                    <select name="choice" style="width:110px"> 
                        <option value="full_name">Name</option>
                        <option value="resume_code">Resume Code</option>
                        <option value="job_title">Job Title</option>
                    </select>
                </td>
                <td width="13%">
                    <input name="search" id="textbox" type="text" />
                </td>
                <td width="5%">
                    <input id="button1" type="submit" value="Search" />
                </td>
                <td width="8%">
                    <a href="#inline" class="fancybox">
                    <input type="button" value="Advanced Search" />
                    </a>
                </td>
                <td width="*%" align="right">&nbsp;</td>
            </tr>
        </table>
        </form>
        </td>
    </tr>

    <tr>
        <td>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td width="7%"><a href="/resume/personal-info">
                    <input id="button4" type="button" value="Add Resume" class="link_button" /></a>
                </td>
                <td width="35%"></td>

                <td width="5%" align="right">&nbsp;</td>
                <td width="30%" align="right">
                    <div id="report"></div>
                </td>
            </tr>
        </table>
        </td>
    </tr>
</table>
<div id="box">
    <?php echo $this->partial ( '/resume/list-resume.phtml', array('rows' => $this->rows, 'paginator' => $this->paginator) )?>
</div>
<?php echo $this->partial ( '/resume/avandced-search.phtml' )?>
<?php echo $this->partial ( '/resume/comment.phtml' )?>
<div id="allcomment" style="width:500px;height: 200px; display: none;">&nbsp;</div>
<div id="detail_resume" style="width:900px;height: 500px; display: none;">&nbsp;</div>
<script type="text/javascript">
$(document).ready(function() {
    //Begin Comment for candidate
	$(".addcomment").fancybox();
	$(".addcomment").click(function(){
		$('#contentcomment').val(''); 
		$('input[name=resume_id]').val($(this).attr('id'));
	});

    $("#insertcomment").click(function(){
        if(!$('#contentcomment').val()) {
            $('#msgcomment').html('Content is not null'); 
            return;
        }
        var resume_id = $('input[name=resume_id]').val();
		$.ajax({
      	  	url: '/resume/save-comment',
        	type: "POST",
			data: { 
                resume_id: resume_id, 
                consultant_id: $('input[name=consultant_id]').val(), 
                content: $('#contentcomment').val()
            },
      	  	success: function(result) {
                $('#viewcomment' + resume_id).html(result);
        	  	$.fancybox.close();
      	  	}
      	});
    });
    
    $(".allcomment").fancybox();
    $(".allcomment").click(function(){
		var resume_id = $(this).attr('id');
		$.ajax({
      	  	url: '/resume/all-comment',
        	type: "POST",
			data: { 
                resume_id: resume_id, 
            },
      	  	success: function(result) {
                $('#allcomment').html(result);
      	  	}
      	});
	});
    //End Comment for candidate

    //Begin View detail candidate
    $(".detail_resume").fancybox();
    $(".detail_resume").click(function(){
		var resume_id = $(this).attr('id');
		$.ajax({
      	  	url: '/resume/detail-resume',
        	type: "POST",
			data: { 
                resume_id: resume_id, 
            },
      	  	success: function(result) {
                $('#detail_resume').html(result);
      	  	}
      	});
	});
    //End View detail candidate
    
    //Begin Avansearch
    $(".fancybox").fancybox();
    $("#avansearch").click(function(){
        var name = $('#full_name').val();
        var email = $('#email').val();
        var phone = $('#phone').val();
        var gender = $('input[name=gender]:radio:checked').val();
        var marital_status = $('input[name=marital_status]:radio:checked').val();
        var job_title = $('#job_title').val();
        var company_name = $('#company_name').val();
        var symbol = $('#symbol').val();
        var salary = $('#salary').val();

        
        //var functions = $('input[name="option[]"]:checkbox:checked');
        var functions = '';
        var checkboxes = $('input[name="option[]"]:checkbox:checked');
        checkboxes.each(function() {
        	if(functions) functions = functions + ',' + $(this).val();
        	else functions = $(this).val();
        });
        
        $.ajax({
      	  	url: '/resume/avandce-search',
        	type: "POST",
			data: { 
                full_name: name, 
                email: email, 
                phone: phone, 
                gender: gender, 
                marital_status: marital_status,
                job_title: job_title,
                company_name: company_name,
                symbol: symbol,
                functions: functions,
                salary: salary
            },
      	  	success: function(result) {
      	    	$('#box').html(result);
        	  	$.fancybox.close();
      	  	}
      	});
    });
    //End Avansearch
    
    $.ajax({
  	  	url: '/resume/resume-report',
  	  	success: function(result) {
  	    	$('#report').html(result);
  	  	}
  	});
});
</script>
<script>
$(document).ready(function(){
    $("#function").click(function(){
        if(($(".multiselect").css('display')) == 'none') $(".multiselect").show('slow');
        else $(".multiselect").hide('slow');
    });
});

$('.multiselect').mouseleave(function(){
    $(".multiselect").hide('slow');
});

jQuery.fn.multiselect = function() {
    $(this).each(function() {
        var checkboxes = $(this).find("input:checkbox");
        checkboxes.each(function() {
            var checkbox = $(this);
           
        });
    });
};

$(".multiselect").multiselect();
</script>