<!-- Add fancyBox main JS and CSS files -->
<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<div class="block-search">
<form id="form" action="/resume" method="post">
	<label>Search</label>
	<select name="choice" style="width:110px"> 
		<option value="full_name">Name</option>
		<option value="resume_code">Resume Code</option>
		<option value="job_title">Job Title</option>
	</select>
	<input type="text" value="" name="search" />
	<input  class="button01" id="button1" type="submit" value="Search" />
	<a href="#inline" class="fancybox" style="text-decoration:none;">
		<input class="button01" type="button" value="Advanced Search" />
	</a>
	<br />
	<br />
	<a href="/resume/personal-info" style="text-decoration:none;">
		<input class="button01" type="button" value="Add Resume" />
	</a>
    <a href="/resume/export-email" style="text-decoration:none;">
        <input class="button01" type="button" value="Export Email" />
    </a>
</form>
</div>  
<p class="today-entry" id="report">&nbsp;</p>
<div id="box">
    <?php echo $this->partial ( '/resume/list-resume.phtml', array('rows' => $this->rows, 'paginator' => $this->paginator) )?>
</div>
<?php echo $this->partial ( '/resume/avandced-search.phtml' )?>
<?php echo $this->partial ( '/resume/comment.phtml' )?>
<div id="allcomment" style="width:500px;height: auto; display: none;overflow:auto;">&nbsp;</div>
<div id="detail_resume" style="width:550px;height: 450px; display: none;">&nbsp;</div>
<script type="text/javascript">
$(document).ready(function() {
    //Begin Comment for candidate
	$(".addcomment").fancybox();
	$(".addcomment").click(function(){
		$('#contentcomment').val(''); 
		$('input[name=resume_id]').val($(this).attr('id'));
	});

    $("#insertcomment").click(function(){
        if(!$('#contentcomment').val()) {
            $('#msgcomment').html('Content is not null'); 
            return;
        }
        var resume_id = $('input[name=resume_id]').val();
		$.ajax({
      	  	url: '/resume/save-comment',
        	type: "POST",
			data: { 
                resume_id: resume_id, 
                consultant_id: $('input[name=consultant_id]').val(), 
                content: $('#contentcomment').val()
            },
      	  	success: function(result) {
                $('#viewcomment' + resume_id).html(result);
        	  	$.fancybox.close();
      	  	}
      	});
    });
    
    $(".allcomment").fancybox({
		'titlePosition'		: 'inside',
		'transitionIn'		: 'none',
		'transitionOut'		: 'none'
	});
    $(".allcomment").click(function(){
		var resume_id = $(this).attr('id');
		$.ajax({
      	  	url: '/resume/all-comment',
        	type: "POST",
			data: { 
                resume_id: resume_id, 
            },
      	  	success: function(result) {
                $('#allcomment').html(result);
      	  	}
      	});
	});
    //End Comment for candidate

    //Begin View detail candidate
    $(".detail_resume").fancybox();
    $(".detail_resume").click(function(){
		$('#detail_resume').html('');
		var resume_id = $(this).attr('id');
		$.ajax({
      	  	url: '/resume/detail-resume',
        	type: "POST",
			data: { 
                resume_id: resume_id, 
            },
      	  	success: function(result) {
                $('#detail_resume').html(result);
      	  	}
      	});
	});
    //End View detail candidate
    
    //Begin Avansearch
    $(".fancybox").fancybox();
    $("#avansearch").click(function(){
        var name = $('#full_name').val();
        var email = $('#email').val();
        var phone = $('#phone').val();
        var gender = $('input[name=gender]:radio:checked').val();
        var marital_status = $('input[name=marital_status]:radio:checked').val();
        var job_title = $('#job_title').val();
        var company_name = $('#company_name').val();
        var symbol = $('#symbol').val();
        var salary = $('#salary').val();

        
        //var functions = $('input[name="option[]"]:checkbox:checked');
        var functions = '';
        var checkboxes = $('input[name="option[]"]:checkbox:checked');
        checkboxes.each(function() {
        	if(functions) functions = functions + ',' + $(this).val();
        	else functions = $(this).val();
        });
        
        $.ajax({
      	  	url: '/resume/avandce-search',
        	type: "POST",
			data: { 
                full_name: name, 
                email: email, 
                phone: phone, 
                gender: gender, 
                marital_status: marital_status,
                job_title: job_title,
                company_name: company_name,
                symbol: symbol,
                functions: functions,
                salary: salary
            },
      	  	success: function(result) {
      	    	$('#box').html(result);
        	  	$.fancybox.close();
      	  	}
      	});
    });
    //End Avansearch
    
    $.ajax({
  	  	url: '/resume/resume-report',
  	  	success: function(result) {
  	    	$('#report').html(result);
  	  	}
  	});
});
</script>
<script>
$(document).ready(function(){
    $("#function").click(function(){
        if(($(".multiselect").css('display')) == 'none') $(".multiselect").show('slow');
    });
});

$("body").click(function(e){
	var $parentClass = $(e.target).parents('.multiselect');
    if(e.target.className !== "function" && $parentClass.length < 1) {
    	$(".multiselect").hide('slow');
    }       
});

jQuery.fn.multiselect = function() {
    $(this).each(function() {
        var checkboxes = $(this).find("input:checkbox");
        checkboxes.each(function() {
            var checkbox = $(this);
           
        });
    });
};

$(".multiselect").multiselect();
</script>