<?php echo $this->partial('resume/menu-add-resume.phtml')?>
<form name="frm" method="post" action="save-resume">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td width="15%">Full Name:<span class="require">*</span></td>
		<td> <input type="text" name="full_name"  style="width: 225px" /></td>
	</tr>
	<tr>
		<td>Birthday:</td>
		<td><input type="text" name="birthday"  style="width: 225px" /></td>
	</tr>		
	<tr>
		<td>Gender:<span class="require">*</span></td>
		<td>
			<input type="radio"	name="gender" id="radio3" value="radio" /> Male &nbsp;&nbsp;&nbsp; 
			<input type="radio" name="gender" id="radio4" value="radio" /> Female
		</td>
	</tr>
	<tr>
		<td>Marital Status:</td>
		<td>
			<input type="radio"	name="marital_status" value="radio" /> Single &nbsp;&nbsp;&nbsp;
			<input type="radio" name="marital_status" value="radio" /> Married &nbsp;&nbsp;&nbsp; 
			<input type="radio" name="marital_status" value="radio" /> Divorced
		</td>
	</tr>
	<tr>
		<td>Email1:</td>
		<td><input type="text" name="email_1"  style="width:225px" /></td>
	</tr>
	<tr>
		<td>Email2:</td>
		<td><input type="text" name="email_2"  style="width:225px" /></td>
	</tr>
	<tr>
		<td>Mobile1:</td>
		<td><input type="text" name="mobile_1"  style="width:225px" /></td>
	</tr>
	<tr>
		<td>Mobile2:</td>
		<td><input type="text" name="mobile_2"  style="width:225px" /></td>
	</tr>
	<tr>
		<td>Telephone:</td>
		<td><input type="text" name="tel" id="textfield3" style="width:225px" /></td>
	</tr>
	<tr>
		<td>Address:</td>
		<td><textarea name="address" rows="5" cols="27"></textarea></td>
	</tr>
	<tr>	
		<td>&nbsp;</td>
		<td>
			<input type="button" name="cancel" value="Cancel" /> &nbsp;&nbsp; 
			<input type="submit" name="next" value="Next &gt;&gt;" />
		</td>
	</tr>
</table>
</form>