Them bang session, file sql nam trong thu muc doc->db->session.sql

<form name="login" method="post" action="user/login">
<table>
    <tr>
        <td>Username </td>
        <td><input type="text" name="user" value="usertest"></td>
    </tr>
    <tr>
        <td>Password </td>
        <td><input type="text" name="password" value="123456"></td>
    </tr>
    <tr>
        <td colspan="2"><input type="submit" name="submit" value="Login"></td>
    </tr>
</table>
</form>