<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Grey Finders | Resume Management System (RMS)</title>
<?php echo $this->headLink();?>
</head>
<body>
<form class="box login" name="login" method="post" action="/user/login">
    <div class="form-login">
    	<h1>LOGIN</h1>
    	<ul>
    		<li>
    			<label>Email <em>*</em></label>
    			<input type="text" tabindex="1" name="email">
    		</li>
    		<li>
    			<label>Password <em>*</em></label>
    			<input type="password" tabindex="2" name="password">
    		</li>
    		<li>
    			<label>&nbsp;</label>
    			<input type="submit" class="button01" class="btnLogin" value="Login" tabindex="3" >
    		</li>
    	</ul>
    </div> 
</form>
</body>
</html>