
<div class="from-add-01" style="width : 400px; float : left;">
<h2><?php echo $this->page_title; ?></h2>
<ul>
	<li>
		<label>Full Name:</label>
		<label><?php echo $this->userInfo['full_name']; ?></label>
	</li>
	<li>
		<label>Job Title:</label>
		<label><?php echo $this->userInfo['job_title']; ?></label>
	</li>
	<li>
		<label>UserName:</label>
		<label><?php echo $this->userInfo['username']; ?></label>
		
	</li>
	<li>
		<label>Phone</label>
		<label><?php echo $this->userInfo['phone']; ?></label>
	</li>
	<li>
		<label>Email:</label>
		<label><?php echo $this->userInfo['email']; ?></label>
		
	</li>
</ul>
<div align="center">
		<a href="/user"><input type="button"  value="cancel" class="button02"></a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<input type="button" id="edit" value="Edit" class="button01"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<input type="button" id="change_password" value="Change Password" class="button01">
</div>
<div id="hide1" style="float:left;width:500px;display:none; ">
<form name="frm" action="/profile/save-user" method="post" onsubmit="return checkValid1()">
<input type="hidden" id="consultant_id" name="id" value="<?php echo $this->userInfo['consultant_id']; ?>">
	<ul>
		<li>
			<label></label>
			<em class="error"></em>
		</li>
		<li>
			<label>Full Name:<em>*</em></label>
			<input type="text" id="full_name" name="full_name" value="<?php echo $this->userInfo['full_name']; ?>">
		</li>
		<li>
			<label>Job Title:</label>
			<input type="text" id="job_title" name="job_title" value="<?php echo $this->userInfo['job_title']; ?>">
		</li>
		<li>
			<label>Phone:</label>
			<input type="text" id="tel" name="tel" value="<?php echo $this->userInfo['phone']; ?>">
		</li>
		<li>
			<label>Email:</label>
			<input type="text" id="email"  name="email" value="<?php echo $this->userInfo['email']; ?>">
		</li>
 	</ul>
 	<div align="center">
 		<input type="button" class="button02" value="cancel" id="cancel"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 		<input type="submit" class="button01" value="Edit" name="submit" >
 	</div>
</form>	
</div>
<div id="hide2" style="float:left;width:500px;display:none;">
	<form action="/user/add-password" method="post" onsubmit="return checkValid2()">
	<input type="hidden" id="consultant_id" name="id" value="<?php echo $this->userInfo['consultant_id']; ?>">
		<ul>
			<li>
			<label></label>
			<em class="false"></em>
			</li>
			<li>
				<label>Old Password:<em>*</em> </label>
				<input type="password" name="password" id="password">
				<em id="check"></em>
			</li>
			<li>
				<label>New Password:<em>*</em> </label>
				<input type="password" name="password1" id="password1">
			</li>
			<li>
				<label>Confirm Password:<em>*</em> </label>
				<input type="password" name="password2" id="password2">
			</li>
		</ul>
		<div align="center">
			<input type="button" id="cancel1" class="button02" value="Cancel"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<input type="submit" class="button01" value="Change">
		</div>
	</form>
</div>
</div>
<script>
	$(document).ready(function(){
		$("#edit").click(function(){
			$("#hide1").show(500);
			$("#hide2").hide(500);
		});
		$("#cancel").click(function(){
			$("#hide1").hide(500);
		});
		$("#change_password").click(function(){
			$("#hide2").show(500);
			$("#hide1").hide(500);
		});
		$("#cancel1").click(function(){
			$("#hide2").hide(500);
		});
	});
</script>
<script>
	function checkValid1()
	{
	var full_name = $("#full_name").val();
	var email = $("#email").val();
	
	if(full_name == '')
	{
		$(".error").html("Please enter your name.");
		return false;
	}
	
	var check = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
    if(!check.test(email))
    {
    	$('.error').html('please enter a valid email address');
    	return false;
    }
    return true;
	}
</script>
<script>
	function checkValid2()
	{	
		alert(2222); return false;
		var password = $("#password").val();
		var password1 = $("#password1").val();
		var password2 = $("#password2").val();
	
				if(password.length == 0)
				{
					$("#check").html("please enter old password.");
					$("#password").focus();
					return false;
				}else{
					$.ajax({
						type : "POST";
						url  : "/user/check-password";
						success : function(result){
							if(result == 0){
								$("#check").html("sai mat khau");
								return false;
								}
							}
					});
				
					if(password1 == ''){
						$(".false").html("please enter new password.");
						$("#password1").focus();
						return false;
						}else{
							if(password1 != password2){
								$(".false").html("mat khau xac nhan khong dung.");
								$("#password2").focus();
								return false;
								}else{return true;}
							}
					}
			return true;
	}
</script>