<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<div class="from-add-01">
<form name="frmAddVacancy" action="/vacancy/save-vacancy" method="post" onsubmit="return checkValid()">
<input type="hidden" name="vacancy_id" id="vacancy_id" value="<?php echo $this->vacancy->getVacancyId();?>"> 
	<h2 style="color:#848484;margin-left:20px;"><?php echo $this->title; ?></h2>
		<ul>
			<li>
				<label></label>
				<em class="error"></em>
			</li>
			<li>
				<label>Company:<em>*</em></label>
				<input type="text" name="company_name" id="company_name" value="<?php echo $this->vacancy->getCompanyName();  ?>">
			</li>
			<li>
				<label>Job Title:</label>
				<input type="text" name="job_title" id="job_title" value="<?php echo $this->vacancy->getJobTitle(); ?>">
			</li>
			<li>
				<label>Salary:</label>
				<input name="min_salary" type="text" id="min_salary" style="width:93px;" value="<?php echo $this->vacancy->getMinSalary(); ?>">
                <input name="max_salary" type="text" id="max_salary" style="width:93px;" value="<?php echo $this->vacancy->getMaxSalary(); ?>"> USD		
			</li>
			
			<li>
				<label>Location:</label>
		        <input type="text" name="location" id="location" value="<?php echo $this->vacancy->getLocation(); ?>">
			</li>
			<li>
				<label>Work Level:</label>
				<input type="text" name="work_level" id="work_level" value="<?php echo $this->vacancy->getWorkLevel(); ?>">
			</li>
			<li>
				<label>Function:</label>
                <input type="text" name="function" id="function" value="<?php echo $this->vacancy->getFunction(); ?>">

			</li>	
            <li>
                <label>Job Description &amp; Requirements:</label>
                <textarea name="desc_reqs" cols="40" rows="20" id="desc_reqs"><?php echo $this->vacancy->getDescReqs();?></textarea>
            </li>		       	
			<li>
				<label></label>
	 			<a href="/vacancy"><input type="button" name="button3" id="button3" value="Cancel" class="button02"></a>
				<input type="submit" name="btSave" id="btSave" value="Save" class="button01">&nbsp;&nbsp;&nbsp;
        		<input type="submit" class="button01" name="btAdd" id="btAdd" value="Save &amp; Add"> &nbsp;&nbsp;&nbsp;
        	</li>
       </ul>
</form>
</div>
<script>
function checkValid()
{
	var company_name = $('#company_name').val();
	if(company_name == '')
	{
		$('.error').html('Please input into field required (*)');
		return false
	}
	
	return true;
}
</script>

