<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<script language="javascript">
function trim(str, chars) {
	return ltrim(rtrim(str, chars), chars);
}
 
function ltrim(str, chars) {
	chars = chars || "\\s";
	return str.replace(new RegExp("^[" + chars + "]+", "g"), "");
}
 
function rtrim(str, chars) {
	chars = chars || "\\s";
	return str.replace(new RegExp("[" + chars + "]+$", "g"), "");
}
</script>
<div class="from-add-01">
<form name="frmAddVacancy" action="/default/vacancy/save-vacancy" method="post">
<input type="hidden" name="vacancy_id" id="vacancy_id" value="<?php echo $this->vacancy_id;?>"> 
	<h2 style="color:#848484;margin-left:20px;"><?php echo $this->title; ?></h2>
		<ul>
			<li>
				<label></label>
				<em class="error"></em>
			</li>
			<li>
				<label>Company:</label>
				<input type="text" name="company_name" id="company_name">
			</li>
			<li>
				<label>Job Title:</label>
				<input type="text" name="job_title" id="job_title" value="<?php echo $this->job_title; ?>">
			</li>
			<li>
				<label>Priority:</label>
				<select name ="priority" id ="priority">
					<option value="4" selected="selected">Low</option>
					<option value="3">Medium</option>
					<option value="2">High</option>
					<option value="1">Urgent</option>
				</select>
			</li>
			<li>
				<label>Salary:</label>
				<input name="min_salary" type="text" id="min_salary" style="width:93px;" value="<?php echo $this->min_salary; ?>">
                <input name="max_salary" type="text" id="max_salary" style="width:93px;" value="<?php echo $this->max_salary; ?>"> USD		
			</li>
			
			<li>
				<label>Location:</label>
		        <input type="text" name="province" id="province">
			</li>
			<li>
				<label>Work Level:</label>
				<input type="text" name="work_level" id="work_level">
			</li>
			<li>
				<label>Function:</label>
                <input type="text" name="function" id="function" value="">

			</li>	
            <li>
                <label>Job Description &amp; Requirements:</label>
                <textarea name="desc_reqs" cols="40" rows="20" id="desc_reqs"><?php echo $this->desc_reqs;?></textarea>
            </li>
		

        
<!--	<div align="center" style="width:992px;clear:both;">-->
			<li>
				<label></label>
	 			<a href="/vacancy"><input type="button" name="button3" id="button3" value="Cancel" class="button02"></a>
				<input type="submit" name="btSave" id="btSave" value="Save" class="button01">&nbsp;&nbsp;&nbsp;
        		<input type="submit" class="button01" name="btAdd" id="btAdd" value="Save &amp; Add"> &nbsp;&nbsp;&nbsp;
        	</li>
       </ul>
	
</form>
</div>

