<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<div class="block-search">
<form id="frmsearch" action="/vacancy" method="post">
	<label>Search</label>
	<input name="txtSearch" type="text" value="<?php echo $this->txtSearch; ?>"/>
    <input class="button01" name="btSearch" type="submit" value="Search"/>
</form>
</div>  
<br />
	<a href="/default/vacancy/add-vacancy" style="text-decoration:none;">
		<input class="button01" type="button" value="Add Vacancy" />
	</a>
<br /><br />

<div id="box">   
    <div class="list-vacancy clearfix" >
        <div class="headVacancy">
            <div class="company">
                <h4>Company</h4>
            </div>
            <div class="job_title" >
                <h4>Job title</h4>
            </div>
            <div class="work_level">
                <h4>Work Level</h4>
            </div>
            <div class="salary">
                <h4>Min Salary</h4>
            </div>
            <div class="salary">
                <h4>Max Salary</h4>
            </div>
            <div class="priority">
                <h4>priority</h4>
            </div>
            <div class="posted">
            	<h4>Posted</h4>
            </div>                    
            <div class="action">
                <h4>Action</h4>
            </div>
        </div>
        <div class="contentVacancy">
        <?php 
			foreach ($this->paginator as $rs) {
		?>
            <div class="company">
            	<a href="/vacancy/view-vacancy/vacancy_id/<?php echo $rs['vacancy_id'] ?>"><strong><?php echo $rs['company_name'] ;?> </strong></a>
            </div>
            <div class="job_title">
            	<?php echo $rs['job_title'];?>
            </div>
            <div class="work_level">
               <?php echo $rs['work_level'] ?>
            </div>
            <div class="salary">
            	<?php echo $rs['min_salary'] ?>
            </div>
             <div class="salary">
            	<?php echo $rs['max_salary'] ?>
            </div>
            <div class="priority">
               <?php echo $rs['priority'] ?>
            </div>
            <div class="posted">
            	<?php echo date("d-m-Y",strtotime($rs['created_date']));?>
            </div>
            <div class="action">
            	<a href="/default/vacancy/add-vacancy/vacancy_id/<?php echo $rs['vacancy_id'];?>">Edit</a>
            </div>
            <?php }?>
        </div>
    </div>
</div>
<?php if(count($this->paginator)) :?>
<div style="clear:both">&nbsp;</div>
<!-- pagging -->
<div class="footer clearfix">
	<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
</div>
<?php endif;?>

