<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<div class="block-search">
<form id="frmsearch" action="/vacancy" method="post">
	<label>Search</label>
	<input name="txtSearch" type="text" value="<?php echo $this->txtSearch; ?>"/>

    <input class="button1" name="btSearch" type="submit" value="Search"/>
</form>
</div>  
<br />
	<a href="/default/vacancy/add-vacancy" style="text-decoration:none;">
		<input class="button01" type="button" value="Add Vacancy" />
	</a>
<br /><br />
<?php
$vacancy = new Default_Model_VacancyMapper();
$company = new Default_Model_CompanyMapper();
$listVacancy = $vacancy->getListVacancy ($this->condition, $this->order_by,($this->currentPage-1)*20,20);
?>
<form name="frmVacancyList">
<input type="hidden" name="listVaId" id="listVaId" value="" />
<div id="box">   
    <div class="list-vacancy clearfix">
        <div class="headVacancy">
            <div class="company">
                <h4>Company</h4>
            </div>
            <div class="checkbox">
                <input name="" type="checkbox" value="" />
            </div>
            <div class="code">
                <h4>Code</h4>
            </div>
            <div class="vacancy">
                <h4>Vacancy</h4>
            </div>
            <div class="salary">
                <h4>Salary</h4>
            </div>
            <div class="location">
                <h4>Location</h4>
            </div>
            <div class="posted">
                <h4>Posted</h4>
            </div>           
            <div class="status">
                <h4>Status</h4>
            </div>
            <div class="cons">
                <h4>Consultant</h4>
            </div>
            <div class="action">
                <h4>Action</h4>
            </div>
        </div>
        <div class="contentVacancy">
        <?php 
			$com_id="";
			foreach ($listVacancy as $rs) {
			$companyname = $company->getFieldValue("company","company_id='".$rs['company_id']."'","full_name_en");
			$companycode = $company->getFieldValue("company","company_id='".$rs['company_id']."'","company_code");
			if ($companyname=="")
				$companyname = $company->getFieldValue("company","company_id='".$rs['company_id']."'","full_name_vn");
			$consultantname = $company->getFieldValue("consultant","consultant_id IN (SELECT consultant_id FROM va_has_consultant WHERE vacancy_id='".$rs['vacancy_id']."' AND inchange_type='Main')","abbreviated_name");
			$location =  $company->getFieldValue("province_lookup","province_id IN(SELECT province_id FROM va_has_location WHERE vacancy_id='".$rs['vacancy_id']."')","name", 0, 1);
			$arr=explode("|",$location);
			?>
        	
            <div class="company">
            <strong><?php if ($com_id=="" || $com_id!=$rs['company_id']) echo $companycode." - ".$companyname; $com_id=$rs['company_id'];?> </strong>
            </div>
            <div class="checkbox">
                <input name="vacancy_id" id="vacancy_id" type="checkbox" value="<?php echo $rs['vacancy_id'];?>" />
            </div>
            <div class="code">
            
            </div>
            <div class="vacancy">
            <h4><a href="/vacancy/vacancy/view-vacancy/vacancy_id/<?php echo $rs['vacancy_id'];?>"><?php echo $rs['job_title'];?></a></h4>
            </div>
            <div class="salary">
            <?php echo $vacancy->getSalaryValue($rs['min_salary'],$rs['max_salary']);?>
            </div>
            <div class="location">
            <?php if (count($arr)==1) echo trim($arr[0]); else
			echo trim($arr[0])." ..." ;?>
            </div>
            <div class="posted">
            <?php echo date("d-m-Y",strtotime($rs['created_date']));?>
            </div>
            <div class="status">
            <?php echo $rs['status'];?>
            </div>
            <div class="cons">
            <?php echo $consultantname;?>
            </div>
            <div class="action">
            <a href="/vacancy/vacancy/add-vacancy/vacancy_id/<?php echo $rs['vacancy_id'];?>">Edit</a>
            </div>
            <?php }?>
        </div>
    </div>
</div>
<?php if(count($this->paginator)) :?>
<div id="box">
	<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
</div>
<?php endif;?>
 </form> 