<div id="adv-search">
<h2>Vacancy Details</h2>
<ul>
    <li>
        <label>Company</label>
        <?php echo $this->vacancy->getCompanyName();?>
    </li>
    <li>
        <label>Company</label>
        <?php echo $this->vacancy->getCompanyName();?>
    </li>
    <li>
        <label>Company</label>
        <?php echo $this->vacancy->getCompanyName();?>
    </li>
    
    <li>
        <label>Company</label>
        <?php echo $this->vacancy->getCompanyName();?>
    </li>
    <li>
        <label>Company</label>
        <?php echo $this->vacancy->getCompanyName();?>
    </li>
    <li>
        <label>Company</label>
        <?php echo $this->vacancy->getCompanyName();?>
    </li>
</ul>
</div>