<table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><form id="form" action="..." method="post">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="5%"><label for="choice">Search : </label></td>
                <td width="6%"><select name="choice">
                    <option>CCode</option>
                </select></td>
                <td width="12%"><input name="text" id="textbox" type="text"/></td>
                <td width="9%"><input id="button1" type="submit" value="Send" /></td>
                <td width="4%"><label for="choice">Filter : </label></td>
                <td width="6%"><select name="choice2">
                    <option>Industry</option>
                </select></td>
                <td width="7%"><select name="choice3">
                    <option>Ranking</option>
                </select></td>
                <td width="9%"><input id="button2" type="submit" value="Ok" /></td>
                <td width="24%">&nbsp;</td>
                <td width="4%"><label for="choice">Sort : </label></td>
                <td width="5%"><select name="choice5">
                  <option>Name</option>
                </select></td>
                <td width="5%"><select name="choice4">
                  <option>ASC</option>
                </select></td>
                <td width="3%"><input id="button3" type="submit" value="Ok" /></td>
              </tr>
            </table>
          </form></td>
        </tr>
        <tr>
          <td height="10"></td>
        </tr>
        <tr>
          <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="6%"><input id="button4" type="submit" value="Add Company" class="add_button" /></td>
              <td width="15%"><input id="button6" type="submit" value="Delete" class="del_button" /></td>
              <td width="33%"><em>Showing 30 of 50 records</em></td>
              <td width="42%" align="right">Month: Apr-2011 <a href="#">(Change)</a> | Open Vacancies: 18 | Candidates in Process: 20</td>
            </tr>
          </table></td>
        </tr>
      </table>
      <div id="box">
        <table width="100%" class="datagrid">
          <thead>
            <tr>
              <th width="36"><input type="checkbox" name="checkbox" id="checkbox" /></th>
              <th width="74" class="a-left">Code</th>
              <th width="160" class="a-left">Company</th>
              <th width="53" class="a-left">Ind</th>
              <th width="53" class="a-left">Rkg</th>

              <th width="53" class="color_bg">Act</th>
              <th width="53" class="color_bg">New<br />
              Vac</th>
              <th width="53" class="color_bg">Open<br />
              Vac</th>
              <th width="53" class="color_bg">Res<br />
              Sent</th>
              <th width="58" class="color_bg">Inter<br />
              view 1</th>
              <th width="58" class="color_bg">Inter<br />
              view +</th>
              <th width="53" class="color_bg">Offer<br />
              Made</th>
              <th width="53" class="color_bg">Offer<br />
              Accpt</th>
              <th width="53" class="color_bg">Joined</th>
              <th width="109" class="a-left">Acc Status</th>
              <th width="94" class="a-left">Cons</th>
              <th width="45" class="a-left">Action</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="a-center"><input type="checkbox" name="checkbox2" id="checkbox2" /></td>
              <td class="a-left">C1234</td>
              <td class="a-left"><a href="#">DHL Viet Nam</a></td>
              <td class="a-left">FNC</td>
              <td class="a-left">A</td>

              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td>&nbsp;</td>
              <td>Thao Nguyen</td>
              <td><a href="#"><img src="images/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="images/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
            </tr>
            <tr>
              <td class="a-center"><input type="checkbox" name="checkbox3" id="checkbox3" /></td>
              <td class="a-left">C1234</td>
              <td class="a-left"><a href="#">DHL Viet Nam</a></td>
              <td class="a-left">FNC</td>
              <td class="a-left">B</td>

              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td>&nbsp;</td>
              <td>Thao Nguyen</td>
              <td><a href="#"><img src="images/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="images/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
            </tr>
            <tr>
              <td class="a-center"><input type="checkbox" name="checkbox4" id="checkbox4" /></td>
              <td class="a-left">C1234</td>
              <td class="a-left"><a href="#">DHL Viet Nam</a></td>
              <td class="a-left">FNC</td>
              <td class="a-left">C</td>

              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td>&nbsp;</td>
              <td>Thao Nguyen</td>
              <td><a href="#"><img src="images/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="images/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
            </tr>
            <tr>
              <td class="a-center"><input type="checkbox" name="checkbox5" id="checkbox5" /></td>
              <td class="a-left">C1234</td>
              <td class="a-left"><a href="#">DHL Viet Nam</a></td>
              <td class="a-left">FNC</td>
              <td class="a-left">A</td>

              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td>&nbsp;</td>
              <td>Thao Nguyen</td>
              <td><a href="#"><img src="images/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="images/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
            </tr>
            <tr>
              <td class="a-center"><input type="checkbox" name="checkbox6" id="checkbox6" /></td>
              <td class="a-left">C1234</td>
              <td class="a-left"><a href="#">DHL Viet Nam</a></td>
              <td class="a-left">FNC</td>
              <td class="a-left">B</td>

              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td>&nbsp;</td>
              <td>Thao Nguyen</td>
              <td><a href="#"><img src="images/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="images/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
            </tr>
            <tr>
              <td class="a-center"><input type="checkbox" name="checkbox7" id="checkbox7" /></td>
              <td class="a-left">C1234</td>
              <td class="a-left"><a href="#">DHL Viet Nam</a></td>
              <td class="a-left">FNC</td>
              <td class="a-left"><a href="#">C</a></td>

              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td>&nbsp;</td>
              <td>Thao Nguyen</td>
              <td><a href="#"><img src="images/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="images/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
            </tr>
            <tr>
              <td class="a-center"><input type="checkbox" name="checkbox8" id="checkbox8" /></td>
              <td class="a-left">C1234</td>
              <td class="a-left"><a href="#">DHL Viet Nam</a></td>
              <td class="a-left">FNC</td>
              <td class="a-left">A</td>

              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td>&nbsp;</td>
              <td>Thao Nguyen</td>
              <td><a href="#"><img src="images/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="images/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
            </tr>
            <tr>
              <td class="a-center"><input type="checkbox" name="checkbox9" id="checkbox9" /></td>
              <td class="a-left">C1234</td>
              <td class="a-left"><a href="#">DHL Viet Nam</a></td>
              <td class="a-left">FNC</td>
              <td class="a-left">B</td>

              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td>&nbsp;</td>
              <td>Thao Nguyen</td>
              <td><a href="#"><img src="images/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="images/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
            </tr>
            <tr>
              <td class="a-center"><input type="checkbox" name="checkbox10" id="checkbox10" /></td>
              <td class="a-left">C1234</td>
              <td class="a-left"><a href="#">DHL Viet Nam</a></td>
              <td class="a-left">FNC</td>
              <td class="a-left"><a href="#">C</a></td>

              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td class="a-center color_bg">&nbsp;</td>
              <td>&nbsp;</td>
              <td>Thao Nguyen</td>
              <td><a href="#"><img src="images/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="images/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
            </tr>
            <tr>
              <td class="a-center"><input type="checkbox" name="checkbox11" id="checkbox11" /></td>
              <td class="a-left">C1234</td>
              <td class="a-left"><a href="#">DHL Viet Nam</a></td>
              <td class="a-left">FNC</td>
              <td class="a-left">A</td>

              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td class="a-center color_bg">23</td>
              <td>&nbsp;</td>
              <td>Thao Nguyen</td>
              <td><a href="#"><img src="images/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="images/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
            </tr>
          </tbody>
        </table>
      </div>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>

                <td width="6%"><input id="button12" type="submit" value="Delete" class="del_button" /></td>
              </tr>
          </table></td>
        </tr>

        <tr>
          <td><form id="form2" action="..." method="post">
              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td width="5%"><label for="choice">Showing</label></td>
                  <td width="4%"><select name="choice6">
                      <option>30</option>
                  </select></td>
                  <td width="91%">records per page</td>
                </tr>
              </table>
          </form></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td align="center">Back&nbsp;&nbsp;|&nbsp;&nbsp;1&nbsp;&nbsp;|&nbsp;&nbsp;2&nbsp;&nbsp;|&nbsp;&nbsp;3&nbsp;&nbsp;|&nbsp;&nbsp;4&nbsp;&nbsp;|&nbsp;&nbsp;5&nbsp;&nbsp;|&nbsp;&nbsp;Next</td>
        </tr>
</table>