<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Grey Finders | Resume Management System (RMS)</title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/stylesheet.css')?>" />
</head>
<body>
<div id="wrapper">
	<div class="top">
		<h1>MANAGE DOCUMENT</h1>
	</div>
	<div class="header clearfix">
	<?php $moduleName = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();  ?>
		<ul class="main-menu">
			<li <?php echo ($moduleName == 'default')? 'class="active"': '' ?>><a href="/resume">Resume</a></li>
			<li <?php echo ($moduleName == 'company')? 'class="active"': '' ?>><a href="/company">Company</a></li>
			<li <?php echo ($moduleName == 'vacancy')? 'class="active"': '' ?>><a href="/vacancy">Vacancy</a></li>
		</ul>
		<div class="user-login">
			<p>Welcome <a href="$"><?php echo $this->username; ?></a></p>
			<a href="/user/logout"><strong>Logout</strong></a>
		</div>
	</div>
	<div class="content clearfix">
