<form name="frmAddContact" method="post" action="" onsubmit="return checkValid()">
<input type="hidden" name="company_id"  id="company_id" value="<?php echo $this->company_id; ?>"/>
<input type="hidden" name="contact_person_id"  id="contact_person_id" value="<?php echo $this->contact_person_id; ?>"/>
<!-- <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><h3><?php echo $this->title_page; ?></h3></td>
      </tr>
      <tr>
        <td height="10"></td>
      </tr>
      <tr>
        <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="79%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td align="right">&nbsp;</td>
                  <td>&nbsp;</td>
                  <td colspan="2" bgcolor="#FFECEC">&nbsp;</td>
                  </tr>
                <tr>
                  <td class="subtitle_popup">Company Name</td>
                  <td>&nbsp;</td>
                  <td width="4%" bgcolor="#FFECEC">&nbsp;</td>
                  <td width="72%" bgcolor="#FFECEC"><strong><?php echo $this->company_name; ?></strong></td>
                </tr>
                <tr>
                  <td class="subtitle_popup">Full Name:<span class="require">*</span></td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td bgcolor="#FFECEC"><select name="title" id="title" style="width:60px">
                    <option value="Mr.">Mr.</option>
                    <option value="Mrs.">Mrs.</option>
                    <option value="Ms.">Ms.</option>
                  </select> <input type="text" name="full_name" id="full_name" style="width:287px" value="<?php echo $this->full_name; ?>"/></td>
                </tr>
                <tr>
                  <td class="subtitle_popup">Job Title:<span class="require">*</span></td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td bgcolor="#FFECEC"><input type="text" name="job_title" id="job_title" style="width:350px" value="<?php echo $this->job_title; ?>"/></td>
                </tr>
                
                <tr>
                  <td valign="top" class="subtitle_popup">Tel 1:</td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td bgcolor="#FFECEC"><input type="text" name="tel_1" id="tel_1" style="width:200px" value="<?php echo $this->tel_1; ?>"/> </td>
                </tr>
				 <tr>
                  <td valign="top" class="subtitle_popup">Tel 2:</td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td bgcolor="#FFECEC"><input type="text" name="tel_2" id="tel_2" style="width:200px" value="<?php echo $this->tel_2; ?>" /> </td>
                </tr>
                <tr>
                  <td class="subtitle_popup">Fax:</td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td bgcolor="#FFECEC"><input type="text" name="fax" id="fax" style="width:200px" value="<?php echo $this->fax; ?>"/></td>
                </tr>
                <tr>
                  <td class="subtitle_popup">Mobile 1:</td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td bgcolor="#FFECEC"><input type="text" name="mobile_1" id="mobile_1" style="width:200px" value="<?php echo $this->mobile_1; ?>"/></td>
                  </tr>
                <tr>
                  <td class="subtitle_popup">Mobile 2:</td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td bgcolor="#FFECEC"><input type="text" name="mobile_2" id="mobile_2" style="width:200px" value="<?php echo $this->mobile_2; ?>" /></td>
                  </tr>
                <tr>
                  <td class="subtitle_popup">Email 1:</td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td bgcolor="#FFECEC"><input type="text" name="email_1" id="email_1" style="width:200px" value="<?php echo $this->email_1; ?>" /></td>
                </tr>
                <tr>
                  <td class="subtitle_popup">Email 2:</td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td bgcolor="#FFECEC"><input type="text" name="email_2" id="email_2" style="width:200px" value="<?php echo $this->email_2; ?>" /></td>
                </tr>
                <tr>
                  <td class="subtitle_popup" valign="top">Address:</td>
                  <td>&nbsp;</td>
                  <td bgcolor="#FFECEC">&nbsp;</td>
                  <td bgcolor="#FFECEC"><textarea name="address" rows="6" id="address" style="width:500px"><?php echo $this->address; ?></textarea></td>
                </tr>
                <tr>
                  <td>&nbsp;</td>
                  <td>&nbsp;</td>
                  <td colspan="2" bgcolor="#FFECEC">&nbsp;</td>
                </tr>
                <tr>
                  <td height="10" colspan="4"></td>
                  </tr>
                <tr>
                  <td>&nbsp;</td>
                  <td>&nbsp;</td>
                  <td colspan="2" align="center"><input type="button" name="btCancel" id="btCancel" value="Cancel" onclick="window.location='/company'"/><?php if($this->contact_person_id==""){?>
&nbsp;&nbsp;&nbsp;
<input type="submit" name="btAddmore" id="btAddmore" value="Save &amp; Add More" /><?php }?>
&nbsp;&nbsp;&nbsp;
<input type="submit" name="btSave" id="btSave" value="Save" /></td>
                </tr>
            </table></td>
            <td>&nbsp;</td>
            <td width="19%" valign="top">&nbsp;</td>
          </tr>
        </table></td>
      </tr>
    </table>
  -->
 <div class="from-add-01">
 <h3><?php echo $this->title_page; ?></h3>
<ul>
	<li>
		<label></label>
		<em class="error"></em>
	</li>
	<li>
		<label>Company Name:</label>
		<label><?php echo $this->company_name; ?></label>
	</li>
	<li>
		<label>Full Name:
			<em>*</em>
		</label>
		
			<select name="title" id="title" style="width:60px;">
				<option value="Mr.">Mr.</option>
				<option value="Mrs.">Mrs.</option>
				<option value="ms.">Ms.</option>
			</select>
		
		
			<input type="text" name="full_name" id="full_name" value="<?php echo $this->contactinfo['full_name']; ?>">
		
	</li>
	<li>
		<label>Job Title:
			<em>*</em>
		</label>
		<label><input type="text" name="job_title" id="job_title" value="<?php echo $this->contactinfo['job_title']; ?>"></label>
	</li>
	<li>
		<label>Tel:</label>
		<label><input type="text" name="tel" id="tel" value="<?php echo $this->contactinfo['tel']; ?>"></label>
	</li>
	<li>
		<label>Fax:</label>
		<label><input type="text" name="fax" id="fax" value="<?php echo $this->contactinfo['fax']; ?>"></label>
	</li>
	<li>
		<label>Mobile:</label>
		<label><input type="text" name="mobile" id="mobile" value="<?php echo $this->contactinfo['mobile']; ?>"></label>
	</li>
	<li>
		<label>Email:</label>
		<label><input type="text" name="email" id="email" value="<?php echo $this->contactinfo['email']; ?>"></label>
	</li>
	<li>
		<label>Address:</label>
		<label>
			<textarea name="address" rows="6" id="address" style="width:500px"><?php echo $this->address; ?></textarea>
		</label>
	</li>
	<li>
		<label></label>
		<input class="button02" type="button" name="btCancel" id="btCancel" value="Cancel" onclick="window.location='/company'"><?php if($this->contact_person_id==""){?> &nbsp;&nbsp;&nbsp;
		<input class="button01" type="submit" name="btAddmore" id="btAddmore" value="Save &amp; Add More" ><?php }?> &nbsp;&nbsp;&nbsp;
		<input class="button02" type="submit" name="btSave" id="btSave" value="Save">
	</li>
</ul>
</div>
</form>
<script>
function checkValid()
{
	var full_name = $("#full_name").val();
	var job_title = $("job_title").val();
    var email = $('#email').val();
   
    if(full_name == '' ||  job_title == ''){
        $('.error').html('Please input into field required (*)');
        return false;
    }

    var check = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
    if(!check.test(email))
    {
    	$('.error').html('please enter a valid email address');
    	return false;
    }
   
    return true;
}   
</script>