<form name="frmAddCompany" method="post" action="/company/save-company" onsubmit="return checkValid()">
<input type="hidden" name="company_id" id="company_id" value="<?php echo $this->company->getCompanyId();?>"/>
<div class="from-add-01" style="100%">
<div style="width:50%;float:left;">
<ul >
	<li>
		<h2><?php echo $this->title;?></h2>
	</li>
	<li>
			<label>&nbsp;</label>
			<em class="error"></em>
	</li>
	<li>
		<label>Company Name:<em>*</em></label>
		<label><input type="text" name="company_name" id="company_name" value="<?php echo $this->company->getCompanyName();?>"></label>
	</li>
	<li>
		<label>Business Type:</label>		
		<input type="text" name="busines_type" id="busines_type" value="<?php echo $this->company->getBusinesType();?>">						
	</li>
	<li>
		<label>Telephone:</label>
		<input type="text" name="tel" id="tel" value="<?php echo $this->company->getTel();?>">
		Ex: 848 38243 780 Ext. 123
	</li>
	<li>
		<label>Fax:</label>
		<input type="text" name="fax" id="fax" value="<?php echo $this->company->getFax();?>">
		Ex: 848 38243 780
	</li>
	<li>
		<label>Email:</label>
		<label><input type="text" name="email" id="email" value="<?php echo $this->company->getEmail();?>"></label>
	</li>
	<li>
		<label>Address:</label>
		<label>
			<input type="text" name="address" id="address" value="<?php echo $this->company->getAddress();?>">
		</label>
	</li>
	<li>
		<label>Website:</label>
		<label><input type="text" name="website" id="website" value="<?php echo $this->company->getWebsite();?>"></label>
	</li>
	<li>
		<label>Company information<br />
		(for internal reference)
		</label>
		<label>
			<textarea name="information" rows="6" id="information" style="width:300px"><?php echo $this->company->getInformation();?></textarea>
		</label>
	</li>
	<li>
		 <label></label>
         <a href="/company" style="text-decoration:none;"><input class="button02" type="button" name="cancel" id="cancel" value="Cancel"></a> &nbsp;&nbsp;&nbsp;
         <input class="button01" type="submit" name="save" id="save" value="Save">
	</li>
</ul>
</div>
<?php if($this->company->getCompanyId() ==''){ ?>
<div style="width:40%; float:left;">
<input type="hidden" name="contact_person_id"  id="contact_person_id" value="<?php echo $this->contactinfo['contact_person_id']; ?>"/>
<ul >
	<li>
		<h2>ADD CONTACT</h2>
	</li>
		<li>
			<label>&nbsp;</label>
			<em></em>
	</li>
	<li>
		<label>Full Name:
			<em>*</em>
		</label>
		
			<select name="title" id="title" style="width:60px;">
				<option value="Mr.">Mr.</option>
				<option value="Mrs.">Mrs.</option>
				<option value="ms.">Ms.</option>
			</select>
			<input type="text" name="full_name" id="full_name" value="<?php echo $this->contactinfo['full_name']; ?>">
		
	</li>
	<li>
		<label>Job Title:
			<em>*</em>
		</label>
		<label><input type="text" name="job_title" id="job_title" value="<?php echo $this->contactinfo['job_title']; ?>"></label>
	</li>
	<li>
		<label>Tel:</label>
		<label><input type="text" name="ct_tel" id="ct_tel" value="<?php echo $this->contactinfo['tel']; ?>"></label>
	</li>
	<li>
		<label>Email:</label>
		<label><input type="text" name="ct_email" id="ct_email" value="<?php echo $this->contactinfo['email']; ?>"></label>
	</li>
</ul>
</div>
<?php } ?>
</div>
</form>
<script>
function checkValid()
{
	var company_name = $("#company_name").val();
	
    var email = $('#email').val();

    if(company_name == '' consultant_id == '') {
        $('.error').html('Please input into field required (*)');
        return false;
    }

    var check = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
    if(!check.test(email))
    {
    	$('.error').html('please enter a valid email address');
    	return false;
    }
   
    return true;
}   
</script>

	



