<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<script>
function checkLogin(){
    $.ajax({
        url: '/resume/check-login',
        success: function(result){
            if(!result) document.location.href = '/user/login';
        }
   });
}
</script>
<div class="block-search">
<form id="frmsearch" action="/company" method="post">
	<label>Search</label>
	<input name="txtSearch" id="txtSearch" type="text" value="<?php echo $this->txtSearch; ?>"/>
    <input class="button01" name="btSearch" type="submit" value="Search"/>
</form>
</div>
<div style="height:40px"> </div>
<div style="clear:both;width:1330px">	
	<div style="width:300px;float:left">
	<a href="/company/add-company" style="text-decoration:none;">
		<input class="button01" type="button" value="Add Company" />
	</a>
        <input class="button01" type="button" value="Add Contact" onclick="addContact()"/>
	</div>
  	<div style="width:250px;float:right">          
	    <label for="choice">Sort : </label>
	    <select name="short_name_id" id="short_name_id" style="width:80px">
	        <option value="full_name_en" <?php if ($this->short_name_id=="full_name_en") echo "selected";?>>Name</option>
	        <option value="created_date" <?php if ($this->short_name_id=="created_date") echo "selected";?>>Created Date</option>
	    </select>
	    <select name="sort_type_id" id="sort_type_id" style="width:60px">
	    	<option value="ASC" <?php if ($this->sort_type_id=="ASC") echo "selected";?>>ASC</option>
	    	<option value="DESC" <?php if ($this->sort_type_id=="DESC") echo "selected";?>>DESC</option>
	    </select>
	    <input type="submit" value="Sort" />
    </div>
</div>
<div style="height:20px;clear:both;"> </div>
<form name="frmCompanyList">
<div id="box">   
    <div class="list-company clearfix">
        <div class="head" style="width:1320px">
            <div class="checkbox" style="width:20px">
                &nbsp;
            </div>
            <div class="name" align="center" style="width:205px">
                <h4>Company Name VN</h4>
            </div>
            <div class="name" align="center" style="width:203px">
                <h4>Company Name EN</h4>
            </div>
            <div class="name" align="center" style="width:190px">
                <h4>address</h4>
            </div>
            <div class="name" style="width:100px;" align="center">
                <h4>tel</h4>
            </div>
            <div class="name" align="center" style="width:190px">
                <h4>email</h4>
            </div>
            <div class="name" style="width:100px;" align="center">
                <h4>Edit</h4>
            </div>
            <div class="name" style="width:100px;" align="center">
                <h4>action</h4>
            </div>
        </div>
        <div class="info-content">
        <?php echo $this->partial('company/list-company.phtml', array('paginator' => $this->paginator)); ?>
        </div>
    </div>
</div>
<div style="clear:both"></div>
  
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
	  <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
		  <tr>
			<td width="5%"><input id="button12" type="submit" value="Delete" class="del_button" /></td>
			<td width="90%">&nbsp;</td>
		  </tr>
	  </table></td>
	</tr>

	<tr>
	  <td></td>
	</tr>
	<?php if(count($this->paginator)) :?>
	<tr>
		<td align="center">
		<div>
            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
		</div></td>
	</tr>
	<?php endif;?>
  </table>
<input type="hidden" name="hdcompany_id" id="hdcompany_id" /> 
 </form>
 <div id="view_company" style="width:700px;height: 450px; overflow-y:scroll; display: none;">&nbsp;</div>
 
<script language="javascript">




 $(document).ready(function() {
     //Begin View detail candidate
     $(".view_company").fancybox();
     $(".view_company").click(function(){
         checkLogin();
         $('#view_company').html('');
         var company_id = $(this).attr('id');
         $.ajax({
             url: '/company/view-company',
             type: "POST",
             data: { 
            	 company_id: company_id, 
             },
             success: function(result) {
                 $('#view_company').html(result);
             }
         });
     });
     //End View detail candidate
 });

</script>