<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<script>
function checkLogin(){
    $.ajax({
        url: '/resume/check-login',
        success: function(result){
            if(!result) document.location.href = '/user/login';
        }
   });
}
</script>
<form id="frmsearch" action="/company" method="post">
<div class="block-search">
	<label>Search</label>
	<input name="txtSearch" id="txtSearch" type="text" value="<?php echo $this->txtSearch; ?>"/>
    <input class="button01" name="btSearch" type="submit" value="Search"/>
</div>
<div style="height:20px"> </div>
<div style="clear:both;width:1330px">	
	<div style="width:300px;float:left">
	<a href="/company/add-company" style="text-decoration:none;">
		<input class="button01" type="button" value="Add Company" />
	</a>
        <input class="button01" type="button" value="Add Contact" onclick="addContact()"/>
	</div>
  	<div style="width:270px;float:right">          
	    <label for="choice">Sort : </label>
	    <select name="sort" id="sort" style="width:110px">
	        <option value="created_date" <?php if ($this->sort=="created_date") echo "selected";?>>Created Date</option>
            <option value="full_name_en" <?php if ($this->sort=="full_name_en") echo "selected";?>>Name</option>
	    </select>
	    <select name="order" id="order" style="width:60px">
	    	<option value="DESC" <?php if ($this->order=="DESC") echo "selected";?>>DESC</option>
            <option value="ASC" <?php if ($this->order=="ASC") echo "selected";?>>ASC</option>
	    </select>
	    <input type="submit" value="Sort" />
    </div>
</div>
</form>
<div style="height:20px;clear:both;"> </div>
<form name="frmCompanyList">
<div id="box">   
    <div class="list-company clearfix">
        <div class="head" style="width:1320px">
            <div class="checkbox" style="width:10px">
                &nbsp;
            </div>
            <div class="name" align="center" style="width:205px">
                <h4>Company Name VN</h4>
            </div>
            <div class="name" align="center" style="width:190px">
                <h4>Company Name EN</h4>
            </div>
            <div class="name" align="center" style="width:190px">
                <h4>address</h4>
            </div>
            <div class="name" style="width:93px;" align="center">
                <h4>tel</h4>
            </div>
            <div class="name" align="center" style="width:170px">
                <h4>email</h4>
            </div>
            <div class="name" style="width:40px;" align="center">
                <h4>Edit</h4>
            </div>
            <div class="name" style="width:210px;" align="center">
                <h4>Comment</h4>
            </div>
        </div>
        <div class="info-content">
        <?php echo $this->partial('company/list-company.phtml', array('paginator' => $this->paginator)); ?>
        </div>
    </div>
</div>
<div style="clear:both"></div>
<!-- pagging -->
<div class="footer clearfix">
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
</div>
</form>
<div id="view_company" style="width:700px;height: 350px; overflow-y:scroll; display: none;">&nbsp;</div>
<?php echo $this->partial ( '/company/comment.phtml' )?> 
<div id="allcomment" style="width:500px;height:200px; overflow-y:scroll; display: none;">&nbsp;</div>
<script language="javascript">
$(document).ready(function() {
     //Begin View detail candidate
     $(".view_company").fancybox();
     $(".view_company").click(function(){
         checkLogin();
         $('#view_company').html('');
         var company_id = $(this).attr('id');
         $.ajax({
             url: '/company/view-company',
             type: "POST",
             data: { 
            	 company_id: company_id, 
             },
             success: function(result) {
                 $('#view_company').html(result);
             }
         });
     });
     //End View detail candidate
 });

$(document).ready(function() {
    //Begin Comment for resume
    $(".addcomment").fancybox();
    $(".addcomment").click(function(){
        $('#contentcomment').val(''); 
        $('input[name=company_id]').val($(this).attr('id'));
    });

    $("#insertcomment").click(function(){
        checkLogin();
        if(!$('#contentcomment').val()) {
            $('#msgcomment').html('Content is not null'); 
            return;
        }
        var company_id = $('input[name=company_id]').val();
        $.ajax({
            url: '/company/save-comment',
            type: "POST",
            data: { 
            	company_id: company_id, 
                consultant_id: $('input[name=consultant_id]').val(), 
                content: $('#contentcomment').val()
            },
            success: function(result) {
                $('#viewcomment' + company_id).html(result);
                $.fancybox.close();
            }
        });
    });
    
    $(".allcomment").fancybox();
    $(".allcomment").click(function(){
        checkLogin();
        var company_id = $(this).attr('id');
        $.ajax({
            url: '/company/all-comment',
            type: "POST",
            data: { 
            	company_id: company_id, 
            },
            success: function(result) {
                $('#allcomment').html(result);
            }
        });
    });
});
    //End Comment for resume
</script>