<!--  bat dau list_company -->
<?php 
$num = 1; 
$companyMapper = new Default_Model_CompanyMapper();
foreach($this->paginator as $rs) { 
    $comment = $companyMapper->getComments($rs['company_id'], 1);
?>
<div class="info-content" style="clear:both">
	<div class="checkbox">
	  <input type="radio" name="company_id" id="company_id" value="<?php echo $rs['company_id']; ?>" onclick="getvalue()" >
	</div>
	<div class="name">
		<a href="#view_company" class="view_company" id="<?php echo $rs['company_id']?>">
            <?php echo $rs['company_name'] ?>&nbsp;		    
        </a>
	</div>
	<div class="name" align="left">
		<?php echo $rs['full_name']; ?>(<?php echo $rs['title']; ?>)<br />	
		<?php echo $rs['job_title']; ?><br />
		<?php echo $rs['mobile']; ?><br />
		<?php echo $rs['ct_email']; ?>
	</div>
	<div class="tel">
		<?php echo $rs['tel'] ?>&nbsp;
	</div>
	<div class="email">
		<?php echo $rs['email'] ?>&nbsp;
	</div>
	<div class="edit">
		<a href="/company/add-company/id/<?php echo $rs['company_id'] ?>" class="editcom">Edit</a>
	</div>
	<div class="action">
        <a href="#comment" class="addcomment" id="<?php echo $rs['company_id']?>">Add Comment</a> &nbsp; &nbsp;
        <a href="#allcomment"  class="allcomment" id="<?php echo $rs['company_id']?>">View all</a>
        <div class="info-comment" id="viewcomment<?php echo $rs['company_id']?>">
            <?php if($comment):?>
            <p>- <?php echo substr($comment['content'], 0, 90);?></p>
            <?php endif;?>
        </div>
    </div>
</div>

<?php $num++; } ?>
<script language="javascript">
check = 0;
function getvalue()
{	
	for(var i=0;i<document.frmCompanyList.companyid.length;i++)
	{	
		
		if(document.frmCompanyList.company_id[i].checked == true)
		{
			check = document.frmCompanyList.company_id[i].value;
			break;
		}
	}
	return check;
}
function addContact()
 {	
	if(check == 0)
	{
		alert("Please select company to add contact.");
	 	exit;
	}else{		
		window.location="/company/add-contact/company_id/"+check;
 	}
 }	
 </script>
 <!-- ket thuc list_company -->