<?php
$contact= new Default_Model_ContactPersonMapper();
$listContact = $contact->getListContact ($this->cominfo['company_id']);
?>
<input type="hidden" id="company_id" value="<?php echo $this->cominfo['company_id']; ?>">
<input type="hidden" id="contact_person_id" value="<?php echo $listContact['contact_person_id']; ?>">
<div style="height :50px;color : #848484; ">
<h2><?php echo $this->cominfo['full_name_vn']; ?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Address : <?php echo $this->cominfo['address']; ?></h2>
</div>
<div class="list-company clearfix">
	<div class="head">
		<div class="status">
			<h4>STT</h4>
		</div>
		<div class="name" style="width:145px;">
			<h4>Full Name</h4>
		</div>
		<div class="name">
			<h4>Job Title</h4>
		</div>
		<div class="name" style="width : 80px;">
			<h4>Tel</h4>
		</div>
		<div class="name" style="width : 195px;">
			<h4>Email</h4>
		</div>
		<div class="name" style="width : 50px;">
			<h4>Edit</h4>
		</div>
	</div>
	
	<?php
    $num=1;
	foreach($listContact as $rs){
    ?>
    <div class="status"><?php echo $num; ?></div>
    <div class="name" style="width:145px;"><?php echo $rs['full_name'];?></div>
    <div class="name"><?php echo $rs['job_title'];?></div>
    <div class="name" style="width : 80px;"><?php echo $rs['tel']; ?></div>
    <div class="name" style="width : 195px;"><?php echo $rs['email']; ?></div>
    <div class="name" style="width : 50px;"><a href="/company/add-contact/contact_person_id/<?php echo $rs['contact_person_id']; ?>">Edit</a></div>
    <?php $num++; }?>
</div>
<div align="center">
	<input type="submit" name="close" class="button01"
			value="Close"
			onclick="event.preventDefault(); parent.$.fancybox.close();" />
</div>

