<div class="from-add-01">
<h2>ADD USER</h2>
	<form name="" action="" onsubmit="return checkValid()">
		<ul>
			<li>
			<label>&nbsp;</label>
			<em class="error"></em>
			</li>
			<li>
				<label>Full Name:<em>*</em></label>
				<select style="width: 60px;" name="">
					<option value="Mr">Mr.</option>
					<option value="Mrs">Mrs.</option>
					<option value="Ms">Ms.</option>
				</select>
				<input id="full_name" type="text" name="full_name" value="<?php echo $this->full_name; ?>" style="width : 185px;">
			</li>
			<li>
				<label>Job title:<em>*</em></label>
				<input id="job_title" type="text" name="job_title" value="<?php echo $this->job_title; ?>">
			</li>
			<li>
				<label>Tel:</label>
				<input type="text" id="tel" name="tel" value="<?php echo $this->tel; ?>">
			</li>
			<li>
				<label>Username:<em>*</em></label>
				<input type="text" id="username" name="username" value="<?php echo $this->username; ?>">
			</li>
			<li>
				<label>Passwork:<em>*</em></label>
				<input type="text" id="" name="" value="">
			</li>
			<li>
				<label></label>
				<input class="button01" type="submit" id="" name="" value="Add user"> &nbsp;&nbsp;&nbsp;&nbsp;
				<input class="button02" type="submit" id="" name="" value="Cancel">
			</li>
		</ul>
	</form>
</div>
<script>
	function checkValid()
	{
		var full_name = $("#full_name").val();
		var username = $("#username").val();
		var passwork = $("#passwork").val();

		if(full_name == '' || username == '' || passwork == '')
		{
			$(".error").html('Please input into field required (*)');
			return false;
		} 
		return true;
	}
</script>