<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
	  <td><form id="form" action="/company" method="post">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
		  <tr>
			<td width="5%"><label for="choice">Search : </label></td>
			<td width="6%"><select name="ccode_id" id="ccode_id" style="width:80px">
				<option value="1">Company Code</option>
                <option value="2">Company Name</option>
			</select></td>
			<td width="12%"><input name="txtSearch" id="txtSearch" type="text"/></td>
			<td width="7%"><select name="industry_id" style="width:100px">
			  <option>Industry</option>
			</select></td>
			<td width="6%"><input id="btSearch" name="btSearch" type="button" value="Ok" /></td>
			<td width="7%">&nbsp;</td>
			<td width="9%">&nbsp;</td>
			<td width="24%">&nbsp;</td>
			<td width="4%"><label for="choice">Sort : </label></td>
			<td width="5%"><select name="sort_name_id" id="sort_name_id" style="width:80px">
			  <option value="full_name_en">Name</option>
              <option value="created_date">Created Date</option>
			</select></td>
			<td width="5%"><select name="sort_type_id" id="sort_type_id" style="width:60px">
			  <option value="ASC">ASC</option>
              <option value="DESC">DESC</option>
			</select></td>
			<td width="3%"><input id="button3" type="submit" value="Ok" /></td>
		  </tr>
		</table>
        <input type="hidden" name="page" id="page" value="1" />
	  </form></td>
	</tr>
	<tr>
	  <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
		<tr>
		  <td width="6%"><input id="btAddCompany" name="btAddCompany" type="button" value="Add Company" class="add_button" /></td>
		  <td width="6%"><input id="btDeleteCompany" name="btDeleteCompany" type="button" value="Delete" class="del_button" /></td>
		  <td width="42%"><em>Showing 30 of 50 records</em></td>
		  <td width="41%" align="right">Month: Apr-2011 <a href="#">(Change)</a> | Open Vacancies: 18 | Candidates in Process: 20</td>
		</tr>
	  </table></td>
	</tr>
  </table>
  <div id="box">
	<table width="100%" class="datagrid">
	  <thead>
		<tr>
		  <th width="26"><input type="checkbox" name="checkbox" id="checkbox" /></th>
		  <th width="57" class="a-left">Code</th>
		  <th width="165" class="a-left">Company</th>
		  <th width="38" class="a-left">Ind</th>
		  <th width="49" class="color_bg">Act</th>
		  <th width="47" class="color_bg">New<br />
		  Vac</th>
		  <th width="51" class="color_bg">Open<br />
		  Vac</th>
		  <th width="50" class="color_bg">Res<br />
		  Sent</th>
		  <th width="50" class="color_bg">Inter<br />
		  view 1</th>
		  <th width="52" class="color_bg">Inter<br />
		  view +</th>
		  <th width="52" class="color_bg">Offer<br />
		  Made</th>
		  <th width="50" class="color_bg">Offer<br />
		  Accpt</th>
		  <th width="53" class="color_bg">Joined</th>
		  <th width="127" class="a-left">Acc Status</th>
		  <th width="104" class="a-left">Cons</th>
		  <th width="60" class="a-left">Action</th>
		</tr>
	  </thead>
	  <tbody>
		<?php echo $this->data; ?>
	  </tbody>
	</table>
  </div>
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
	  <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
		  <tr>
			<td width="5%"><input id="button12" type="submit" value="Delete" class="del_button" /></td>
			<td width="90%">&nbsp;</td>
		  </tr>
	  </table></td>
	</tr>

	<tr>
	  <td></td>
	</tr>
	<tr>
	  <td align="center"><div id="box">
     <?php echo $this->partial ( '/company/index.phtml', array('rows' => $this->rows, 'paginator' => $this->paginator) )?>
</div></td>
	</tr>
  </table>