<div class="from-add-01" style="width:900px;">
<form method="post" action="<?php echo $this->url(array('module' => 'vacancy', 'controller' => 'index', 'action' => 'add-vacancy'), 'vacancy-add-router', true)?>">
	<h2>ADD VACANCY</h2>
	<div id="head" style="background-color:#8DC54C;width:900px;"><h2>VACANCY DETAILS</h2></div>
	<div id="left" style="float:left;width:550px;">
		<ul>
			<li>
				<label>Consultant:<em>*</em></label>
				<select name="vacancy[va_has_consultant][consultant_id]" id="consultant_id">
											<option value="0">--Select Consultant--</option>
											<?php if($this->consultants):?>
											<?php foreach ($this->consultants as $consultant):?>
											<option value="<?php echo $consultant->consultant_id?>"><?php echo $consultant->full_name?></option>
											<?php endforeach;?>
											<?php endif;?>
				</select>
			</li>
			<li>
				<label>Company:<em>*</em></label>
				<select name="vacancy[company_id]" id="company_id">
											<option value="0">--Select Company--</option>
											<?php if($this->companies):?>
											<?php foreach ($this->companies as $company):?>
											<option value="<?php echo $company->company_id?>"><?php echo $company->full_name_en?></option>
											<?php endforeach;?>
											<?php endif;?>
				</select>
			</li>
			<li>
				<label>Job Title:<em>*</em></label>
				<input type="text" name="vacancy[job_title]"
											id="job_title" >
			</li>
			<li>
				<label># of Vacancies:</label>
				<input name="vacancy[no_of_vacancies]" type="text"
											id="no_of_vacancies" value="1">
			</li>
			<li>
				<label>Salary:<em>*</em></label>
				<select name="vacancy[displayed_salary]" id="displayed_salary">
											<?php foreach ($this->displaySalaryConfig as $dSC):?>
											<option value="<?php echo $dSC?>"><?php echo $dSC?></option>
											<?php endforeach;?>
				</select>
				<input name="vacancy[estimated_salary" type="text" id="estimated_salary" value="1"> USD		
			</li>
			<li>
				<label>Estimated Salary:<em>*</em></label>
				<input name="vacancy[estimated_salary" type="text" id="estimated_salary" value="1"> USD (for internal reference only)
			</li>
			<li>
				<label>Location:<em>*</em></label>
				<select name="select4" id="select4">
					<option></option>
				</select>
			</li>
			<li>
				<label>Work Level:<em>*</em></label>
				<select name="select5" id="select5">
					<option></option>
				</select>
			</li>
			<li>
				<label>Function:<em>*</em></label>
			
			<select name="select6" id="select6">
				<option></option>
			</select>
			</li>
			<li>
				<label>Public:<em>*</em></label>
				<input type="radio" name="radio" id="radio5" value="radio"> Yes, Public&nbsp;&nbsp;
				<input type="radio" name="radio" id="radio6" value="radio"> No, Confidential
			</li>
			<li>
				<label>Status:<em>*</em></label>
				<select name="select7" id="select7">
					<option></option>
				</select>
			</li>
		</ul>
	</div>
	<div style="float:left;width:350px;">
		Job Description &amp; Requirements:
		<textarea name="textfield5" cols="50" rows="20" id="textfield5"></textarea>
	</div>
	<div style="clear:both;width:900px;background-color:#8DC54C;">
		<h2>COMPANY INFORMATION</h2>
	</div>
	<div>
		<ul>
			<li>
				<label>Company Information <br />
				(will be shown with job postings):
				</label>
				<label>
					<textarea name="textfield6" cols="60" rows="5" id="textfield6">
						Company is an Executive Search &amp; Recruitment agency in four main industries: consumer goods &amp; services, finance &amp; banking, ICT, and industrial; a division of Grey Finders and a partner of Glasford International, a global collaboration of independent executive search firms, operating successfully over 30 countries throughout Europe, the Americas, Middle East, Far-East &amp; Africa. Our client is
						 INSERT DESCRIPTION ABOUT THE COMPANY HERE: 
					</textarea>
				</label>
				<label>
				Notice:
				<strong>Updated information will be shown in all job postings of the same company.</strong>
				</label>
			</li>
		</ul>
	</div>
	<div align="center" style="width:900px;">
		<input type="submit" name="button" id="button" value="Save" class="del_button">&nbsp;&nbsp;&nbsp;
		<input type="submit" class="add_button" name="button2" id="button2" value="Save &amp; Add"> &nbsp;&nbsp;&nbsp;
		<input type="submit" name="button3" id="button3" value="Cancel" class="del_button" >
	</div>
</form>
</div>
