<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<div class="block-search">
<form id="frmsearch" action="/vacancy" method="post">
	<label>Search</label>
	<select name="ccode_id" id="ccode_id" style="width:125px">
				<option value="1" <?php if ($this->ccode_id==1) echo "selected";?> >Vacancy Code</option>
                <option value="2" <?php if ($this->ccode_id==2) echo "selected";?>>Job Title</option>
			</select>
	<input name="txtSearch" id="txtSearch" type="text" value="<?php echo $this->txtSearch; ?>"/>
	<select name="status" id="status" style="width:80px">
    		  <option value="0">Status</option>
			  <option value="Open">Open</option>
              <option value="Close">Close</option>
	</select>
    <input id="btSearch" name="btSearch" type="submit" value="Search" style="margin-right:420px"/>
    <input type="hidden" name="page" id="page" value="1" />
    
</form>
</div>  <br />
<p class="today-entry" id="report">Public: <strong><?php echo $this->totalPublic; ?></strong> | Confidential: <strong><?php echo $this->totalConfidential; ?></strong> | Total Open: <strong><?php echo $this->totalOpen; ?></strong></p>
	<br />
	<a href="/vacancy/vacancy/add-vacancy" style="text-decoration:none;">
		<input class="button01" type="button" value="Add Vacancy" />
	</a>
        <input class="button01" type="button" value="Close" id="btClose"/>
        <input class="button01" type="button" value="Delete" />
        <a href="/vacancy/vacancy/manage-candidate" style="text-decoration:none;">
		<input class="button01" type="button" value="Manage Candidates" />
	</a>
    <br />
<br />
<?php
$vacancy = new Vacancy_Model_VacancyMapper();
$company = new Company_Model_CompanyMapper();
$listVacancy = $vacancy->getListVacancy ($this->condition, $this->order_by,($this->currentPage-1)*20,20);
?>
<form name="frmVacancyList">
<input type="hidden" name="listVaId" id="listVaId" value="" />
<div id="box">   
    <div class="list-vacancy clearfix">
        <div class="headVacancy">
            <div class="company">
                <h4>Company</h4>
            </div>
            <div class="checkbox">
                <input name="" type="checkbox" value="" />
            </div>
            <div class="code">
                <h4>Code</h4>
            </div>
            <div class="vacancy">
                <h4>Vacancy</h4>
            </div>
            <div class="salary">
                <h4>Salary</h4>
            </div>
            <div class="location">
                <h4>Location</h4>
            </div>
            <div class="process">
                <h4>Process</h4>
            </div>
            <div class="posted">
                <h4>Posted</h4>
            </div>           
            <div class="status">
                <h4>Status</h4>
            </div>
            <div class="cons">
                <h4>Consultant</h4>
            </div>
            <div class="action">
                <h4>Action</h4>
            </div>
        </div>
        <div class="contentVacancy">
        <?php 
			$com_id="";
			foreach ($listVacancy as $rs) {
			$companyname = $company->getFieldValue("company","company_id='".$rs['company_id']."'","full_name_en");
			$companycode = $company->getFieldValue("company","company_id='".$rs['company_id']."'","company_code");
			if ($companyname=="")
				$companyname = $company->getFieldValue("company","company_id='".$rs['company_id']."'","full_name_vn");
			$consultantname = $company->getFieldValue("consultant","consultant_id IN (SELECT consultant_id FROM va_has_consultant WHERE vacancy_id='".$rs['vacancy_id']."' AND inchange_type='Main')","abbreviated_name");
			//$status = $company->getFieldValue("va_has_consultant"," vacancy_id='".$rs['vacancy_id']."' AND inchange_type='Main'","status");
			$location =  $company->getFieldValue("province_lookup","province_id IN(SELECT province_id FROM va_has_location WHERE vacancy_id='".$rs['vacancy_id']."')","name", 0, 1);
			$arr=explode("|",$location);
			$resume_process_id = $company->getFieldValue("candidate_has_process","candidate_process_id IN (SELECT max(cp.candidate_process_id ) FROM candidate_has_process cp WHERE cp.candidate_id IN (SELECT c.candidate_id FROM candidate c WHERE vacancy_id = '".$rs['vacancy_id']."'))","resume_process_id", 0, 1);
			$process =  $company->getFieldValue("resume_process_lookup","resume_process_id ='$resume_process_id'","name", 0, 1);
			?>
        	
            <div class="company">
            <strong><?php if ($com_id=="" || $com_id!=$rs['company_id']) echo $companycode." - ".$companyname; $com_id=$rs['company_id'];?> </strong>
            </div>
            <div class="checkbox">
                <input name="vacancy_id" id="vacancy_id" type="checkbox" value="<?php echo $rs['vacancy_id'];?>" />
            </div>
            <div class="code">
            <?php echo $rs['vacancy_code'];?>
            </div>
            <div class="vacancy">
            <h4><a href="/vacancy/vacancy/view-vacancy/vacancy_id/<?php echo $rs['vacancy_id'];?>"><?php echo $rs['job_title'];?></a></h4>
            </div>
            <div class="salary">
            <?php echo $vacancy->getSalaryValue($rs['min_salary'],$rs['max_salary']);?>
            </div>
            <div class="location">
            <?php if (count($arr)==1) echo trim($arr[0]); else
			echo trim($arr[0])." ..." ;?>
            </div>
            <div class="process">
            <?php echo $process;?>
            </div>
            <div class="posted">
            <?php echo date("d-m-Y",strtotime($rs['created_date']));?>
            </div>
            <div class="status">
            <?php echo $rs['status'];?>
            </div>
            <div class="cons">
            <?php echo $consultantname;?>
            </div>
            <div class="action">
            <a href="/vacancy/vacancy/add-vacancy/vacancy_id/<?php echo $rs['vacancy_id'];?>">Edit</a>
            </div>
            <?php }?>
        </div>
    </div>
</div>
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
	<?php if(count($this->paginator)) :?>
	<tr>
		<td align="center"><div id="box">
            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
		</div></td>
	</tr>
	<?php endif;?>
  </table>
 </form>
 <script language="javascript">
 function getValueListCheckBox(list,id)
{	
	if(list!=undefined){
	var num=list.length;
	if (num==undefined)
	{
		if (list.checked)
			id.value=list.value;
		else
			id.value="";
	}
	else
		{
			count=0;
			str="";
			for (i=0;i<num;i++)
			{
				if (list[i].checked)
				{
					if (count==0)
						str=list[i].value;
					else
						str = str + ", " + list[i].value;
					count++;
				}
			}
		id.value=str;
       }
	}
	alert(id.value);
}
$(document).ready(function() {
	 $("#btClose").click(function(){
			getValueListCheckBox(document.frmVacancyList.vacancy_id,document.frmVacancyList.listVaId);

			$.ajax({
				url: '/vacancy/vacancy/close-vacancy',
				type: "POST",
				data: { 
					listvacancyid: document.frmVacancyList.listVaId
				},
				success: function(result) {
					location.reload();
				}
			});
		});
 });
 </script>