<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
	  <td><form id="form" action="../..." method="post">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
		  <tr>
			<td width="5%"><label for="choice">Search : </label></td>
			<td width="6%"><select name="choice" style="width:80px">
				<option>VCode</option>
			</select></td>
			<td width="12%"><input name="text" id="textbox" type="text"/></td>
			<td width="6%"><select name="choice2" style="width:80px">
			  <option>Open</option>
							</select></td>
			<td><input id="button1" type="submit" value="Search" /></td>
			</tr>
		</table>
	  </form></td>
	</tr>
	<tr>
	  <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
		<tr>
		  <td width="7%"><input id="button4" type="submit" value="Add Vacancy" class="link_button" /></td>
		  <td width="4%"><input id="button2" type="submit" value="Close" class="link_button" /></td>
		  <td width="6%"><input id="button3" type="submit" value="Delete" class="link_button" /></td>
		  <td width="23%"><em>Showing 30 of 50 records</em></td>
		  <td width="44%" align="right">Public: <strong>18</strong> | Confidential: <strong>20</strong> | Total Open: <strong>38</strong></td>
		  <td width="5%" align="right"><strong>Sort :                </strong></td>
		  <td width="5%" align="right"><select name="choice3" style="width:80px">
			<option>Priority</option>
		  </select></td>
		</tr>
	  </table></td>
	</tr>
  </table>
  <div id="box">
	<table width="100%" class="datagrid">
	  <thead>
		<tr>
		  <th width="242" class="a-left">Company</th>
		  <th width="57" class="a-left">Code</th>
		  <th width="24"><input type="checkbox" name="checkbox" id="checkbox" /></th>
		  <th width="226" class="a-left">Vacancy</th>
		  <th width="26" class="a-left">PR</th>
		  <th width="80" class="a-left">Salary</th>
		  <th width="91" class="a-left">Location</th>
		  <th width="112" class="a-left">Process</th>
		  <th width="78" class="a-left">Posted</th>
		  <th width="39">Public</th>
		  <th width="60" class="a-left">Status</th>
		  <th width="93" class="a-left">Cons</th>
		  <th width="64" class="a-left">Action</th>
		</tr>
	  </thead>
	  <tbody>
		<tr>
		  <td rowspan="5" valign="top" class="a-left"><strong>British American Tobacco</strong><br />
		  C1234</td>
		  <td class="a-left">C1234</td>
		  <td class="a-center"><input type="checkbox" name="checkbox2" id="checkbox2" /></td>
		  <td class="a-left"><a href="#">IT Project Management</a></td>
		  <td class="a-center"><ul class="pr_red"><li></li></ul></td>
		  <td class="a-left">$600 - $800</td>
		  <td>Ho Chi Minh</td>
		  <td class="datagrid">Resume sent</td>
		  <td>01-01-2011</td>
		  <td class="a-center">P</td>
		  <td class="text_green">Open</td>
		  <td>Thao Nguyen</td>
		  <td><a href="#"><img src="../img/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="../img/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
		</tr>
		<tr>
		  <td class="a-left">C1234</td>
		  <td class="a-center"><input type="checkbox" name="checkbox3" id="checkbox3" /></td>
		  <td class="a-left"><a href="#">IT Project Management</a></td>
		  <td class="a-center"><ul class="pr_red"><li></li></ul></td>
		  <td class="a-left">$600 - $800</td>
		  <td>Ho Chi Minh</td>
		  <td>Resume sent</td>
		  <td>01-01-2011</td>
		  <td class="a-center">P</td>
		  <td class="text_green">Open</td>
		  <td>Thao Nguyen</td>
		  <td><a href="#"><img src="../img/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="../img/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
		</tr>
		<tr>
		  <td class="a-left">C1234</td>
		  <td class="a-center"><input type="checkbox" name="checkbox4" id="checkbox4" /></td>
		  <td class="a-left"><a href="#">IT Project Management</a></td>
		  <td class="a-center"><ul class="pr_red"><li></li></ul></td>
		  <td class="a-left">$600 - $800</td>
		  <td>Ho Chi Minh</td>
		  <td>Client interview 1 </td>
		  <td>01-01-2011</td>
		  <td class="a-center">P</td>
		  <td class="text_green">Open</td>
		  <td>Thao Nguyen</td>
		  <td><a href="#"><img src="../img/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="../img/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
		</tr>
		<tr>
		  <td class="a-left">C1234</td>
		  <td class="a-center"><input type="checkbox" name="checkbox5" id="checkbox5" /></td>
		  <td class="a-left"><a href="#">IT Project Management</a></td>
		  <td class="a-center"><ul class="pr_yellow"><li></li></ul></td>
		  <td class="a-left">$600 - $800</td>
		  <td>Ho Chi Minh</td>
		  <td>Client interview 1 </td>
		  <td>01-01-2011</td>
		  <td class="a-center">P</td>
		  <td class="text_green">Open</td>
		  <td>Thao Nguyen</td>
		  <td><a href="#"><img src="../img/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="../img/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
		</tr>
		<tr>
		  <td class="a-left">C1234</td>
		  <td class="a-center"><input type="checkbox" name="checkbox6" id="checkbox6" /></td>
		  <td class="a-left"><a href="#">IT Project Management</a></td>
		  <td class="a-center"><ul class="pr_yellow"><li></li></ul></td>
		  <td class="a-left">$600 - $800</td>
		  <td>Ho Chi Minh</td>
		  <td>Successful </td>
		  <td>01-01-2011</td>
		  <td class="a-center">P</td>
		  <td class="text_green">Open</td>
		  <td>Thao Nguyen</td>
		  <td><a href="#"><img src="../img/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="../img/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
		</tr>
		<tr>
		  <td rowspan="3" valign="top" class="a-left"><strong>Suzuki Vietnam</strong><br />
		  C1235</td>
		  <td class="a-left">C1234</td>
		  <td class="a-center"><input type="checkbox" name="checkbox7" id="checkbox7" /></td>
		  <td class="a-left"><a href="#">IT Project Management</a></td>
		  <td class="a-center"><ul class="pr_yellow"><li></li></ul></td>
		  <td class="a-left">$600 - $800</td>
		  <td>Ho Chi Minh</td>
		  <td>Successful </td>
		  <td>01-01-2011</td>
		  <td class="a-center text_red">C</td>
		  <td class="text_green">Open</td>
		  <td>Thao Nguyen</td>
		  <td><a href="#"><img src="../img/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="../img/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
		</tr>
		<tr>
		  <td class="a-left">C1234</td>
		  <td class="a-center"><input type="checkbox" name="checkbox8" id="checkbox8" /></td>
		  <td class="a-left"><a href="#">IT Project Management</a></td>
		  <td class="a-center"><ul class="pr_violet"><li></li></ul></td>
		  <td class="a-left">$600 - $800</td>
		  <td>Ho Chi Minh</td>
		  <td>Successful </td>
		  <td>01-01-2011</td>
		  <td class="a-center text_red">C</td>
		  <td>Closed</td>
		  <td>Thao Nguyen</td>
		  <td><a href="#"><img src="../img/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="../img/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
		</tr>
		<tr>
		  <td class="a-left">C1234</td>
		  <td class="a-center"><input type="checkbox" name="checkbox9" id="checkbox9" /></td>
		  <td class="a-left"><a href="#">IT Project Management</a></td>
		  <td class="a-center"><ul class="pr_violet"><li></li></ul></td>
		  <td class="a-left">$600 - $800</td>
		  <td>Ho Chi Minh</td>
		  <td>Successful </td>
		  <td>01-01-2011</td>
		  <td class="a-center text_red">C</td>
		  <td>Closed</td>
		  <td>Thao Nguyen</td>
		  <td><a href="#"><img src="../img/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="../img/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
		</tr>
		<tr>
		  <td rowspan="2" valign="top" class="a-left"><strong>Zuellig Pharma</strong><br />
		  C1235</td>
		  <td class="a-left">C1234</td>
		  <td class="a-center"><input type="checkbox" name="checkbox10" id="checkbox10" /></td>
		  <td class="a-left"><a href="#">IT Project Management</a></td>
		  <td class="a-center"><ul class="pr_grey"><li></li></ul></td>
		  <td class="a-left">$600 - $800</td>
		  <td>Ho Chi Minh</td>
		  <td>Successful </td>
		  <td>01-01-2011</td>
		  <td class="a-center text_red">C</td>
		  <td>Closed</td>
		  <td>Thao Nguyen</td>
		  <td><a href="#"><img src="../img/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="../img/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
		</tr>
		<tr>
		  <td class="a-left">C1234</td>
		  <td class="a-center"><input type="checkbox" name="checkbox11" id="checkbox11" /></td>
		  <td class="a-left"><a href="#">IT Project Management</a></td>
		  <td class="a-center"><ul class="pr_grey"><li></li></ul></td>
		  <td class="a-left">$600 - $800</td>
		  <td>Ho Chi Minh</td>
		  <td>Offer accepted</td>
		  <td>01-01-2011</td>
		  <td class="a-center text_red">C</td>
		  <td>Closed</td>
		  <td>Thao Nguyen</td>
		  <td><a href="#"><img src="../img/icons/user.png" title="Show profile" width="16" height="16" /></a><a href="#"><img src="../img/icons/user_edit.png" title="Edit user" width="16" height="16" /></a></td>
		</tr>
	  </tbody>
	</table>
  </div>
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
	  <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
		  <tr>
			<td width="4%"><input id="button12" type="submit" value="Close" class="link_button" /></td>
			<td width="6%"><input id="button7" type="submit" value="Delete" class="link_button" /></td>
			<td width="84%">&nbsp;</td>
		  </tr>
	  </table></td>
	</tr>
	
	<tr>
	  <td><form id="form2" action="../..." method="post">
		  <table width="100%" border="0" cellspacing="0" cellpadding="0">
			<tr>
			  <td width="5%"><label for="choice">Showing</label></td>
			  <td width="4%"><select name="choice6">
				  <option>30</option>
			  </select></td>
			  <td width="91%">records per page</td>
			</tr>
		  </table>
	  </form></td>
	</tr>
	<tr>
	  <td align="center">Back&nbsp;&nbsp;|&nbsp;&nbsp;1&nbsp;&nbsp;|&nbsp;&nbsp;2&nbsp;&nbsp;|&nbsp;&nbsp;3&nbsp;&nbsp;|&nbsp;&nbsp;4&nbsp;&nbsp;|&nbsp;&nbsp;5&nbsp;&nbsp;|&nbsp;&nbsp;Next</td>
	</tr>
  </table>