<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<div class="block-search">
<form id="frmsearch" action="/vacancy" method="post">
	<label>Search</label>
	<input name="txtSearch" type="text" value="<?php echo $this->txtSearch; ?>"/>

    <input class="button1" name="btSearch" type="submit" value="Search"/>
</form>
</div>  
<br />
	<a href="/default/vacancy/add-vacancy" style="text-decoration:none;">
		<input class="button01" type="button" value="Add Vacancy" />
	</a>
<br /><br />

<form name="frmVacancyList">
<input type="hidden" name="vacancy_id" id="vacancy_id" value="<?php echo $this->$vacancy['vacancy_id'] ?>" />
<div id="box">   
    <div class="list-vacancy clearfix" >
        <div class="headVacancy" style="width:100%;align:left">
            <div class="company" style="width:13%;align:left">
                <h4>Company</h4>
            </div>
            <div class="vacancy" style="width:6%;align:left">
                <h4>Job_title</h4>
            </div>
            <div class="vacancy" style="width:7%;align:left">
                <h4>Work Level</h4>
            </div>
            <div class="salary" style="width:7%;align:left">
                <h4>Min Salary</h4>
            </div>
            <div class="salary" style="width:7%;align:left">
                <h4>Max Salary</h4>
            </div>
            <div class="salary" style="width:6%;align:left">
                <h4>priority</h4>
            </div>
            <div class="location" style="width:10%;align:left">
                <h4>Location</h4>
            </div>
            <div class="posted" style="width:7%;align:left">
            	<h4>Posted</h4>
            </div>
            <div class="salary" style="width:8%;align:left">
                <h4>Function</h4>
            </div>           
            <div class="action" style="width:8%;align:left">
                <h4>Action</h4>
            </div>
        </div>
        <div class="contentVacancy">
        <?php 
			foreach ($this->vacancy as $rs) {
		?>
        	
            <div class="company" style="width:13%;align:left">
            	<strong><?php echo $rs['company_name'] ;?> </strong>
            </div>
            <div class="vacancy" style="width:6%;align:left">
            	<?php echo $rs['job_title'];?>
            </div>
            <div class="vacancy" style="width:7%;align:left">
                <h4>Work Level</h4>
            </div>
            <div class="salary" style="width:7%;align:left">
            	<?php echo $rs['min_salary'] ?>
            </div>
             <div class="salary" style="width:7%;align:left">
            	<?php echo $rs['max_salary'] ?>
            </div>
            <div class="salary" style="width:6%;align:left">
               <?php echo $rs['priority'] ?>
            </div>
            <div class="location" style="width:10%;align:left">
            	<?php echo $rs['location']  ?>
            </div>
            <div class="posted" style="width:7%;align:left">
            	<?php echo date("d-m-Y",strtotime($rs['created_date']));?>
            </div>
            <div class="salary" style="width:8%;align:left">
            	<?php echo $rs['function'];?>
            </div>
            <div class="action" style="width:8%;align:left">
            	<a href="/default/vacancy/add-vacancy/vacancy_id/<?php echo $rs['vacancy_id'];?>">Edit</a>
            </div>
            <?php }?>
        </div>
    </div>
</div>
<?php if(count($this->paginator)) :?>
<div id="box">
	<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
</div>
<?php endif;?>
 </form> 