
<div class="from-add-01">
<h2>ADD USER</h2>
	<form name="frmuser" action="/profile/save-user" method="post" onsubmit="return checkValid()">
		<ul>
			<li>
			<label>&nbsp;</label>
			<em class="error"></em>
			</li>
			<li>
				<label>Full Name:<em>*</em></label>
				<select style="width: 60px;" name="title">
					<option value="Mr.">Mr.</option>
					<option value="Mrs.">Mrs.</option>
					<option value="Ms.">Ms.</option>
				</select>
				<input id="full_name" type="text" name="full_name" value="<?php echo $this->full_name; ?>" style="width : 185px;">
			</li>
			<li>
				<label>Job title:</label>
				<input id="job_title" type="text" name="job_title" value="<?php echo $this->job_title; ?>">
			</li>
			<li>
				<label>Tel:</label>
				<input type="text" id="tel" name="tel" value="<?php echo $this->tel; ?>">
			</li>
			<li>
				<label>Username:<em>*</em></label>
				<input type="text" id="username" name="username" value="<?php if(isset($_POST['username'])) echo $_POST['username']; ?>">
			</li>
			<li>
				<label>Password:<em>*</em></label>
				<input type="password" id="password" name="password">
			</li>
			<li>
				<label>Email:</label>
				<input type="text" id="email" name="email" value="<?php echo $this->email; ?>">
			</li>
			<li>
				<label></label>
				<input class="button01" type="submit" id="" name="add" value="Add user"> &nbsp;&nbsp;&nbsp;&nbsp;
				<a href="/profile" style="text-decoration:none;"><input class="button02" type="button"  value="Cancel"></a>
			</li>
		</ul>
	</form>
</div>
<script>
	function checkValid()
	{
		var full_name = $("#full_name").val();
		var username = $("#username").val();
		var passwork = $("#password").val();
		var email = $('#email').val();
		
		if(full_name == '' || username == '' || password == '')
		{
			$(".error").html('Please input into field required (*)');
			return false;
		} 

		 var check = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
		    if(!check.test(email))
		    {
		    	$('.error').html('please enter a valid email address');
		    	return false;
		    }
		    
		return true;
	}
</script>