<!-- Add fancyBox main JS and CSS files -->
<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<div>
<a href="/profile/add-user" style="text-decoration:none;">
	<input class="button01" type="button" value="Add User" />
</a>
</div>
<br />
<div id="userManagement">
	<div id="box">
	    <div class="list-company clearfix">
	        <div class="head">
	            <div class="checkbox">
	                <input type="checkbox" name="" />
	            </div>
	            <div class="username">
	                <h4>Username</h4>
	            </div>
	            <div class="fullname">
	                <h4>Fullname</h4>
	            </div>
	            <div class="email">
	                <h4>Email</h4>
	            </div>
	            <div class="job-title">
	                <h4>Job Title</h4>
	            </div>
	            <div class="status">
	                <h4>Status</h4>
	            </div>
	            <div class="admin">
	                <h4>Admin</h4>
	            </div>
				<div class="action">
	                <h4>Action</h4>
	            </div>
	            <div class="modified-date">
	                <h4>Modified Date</h4>
	            </div>
	        </div>
	        <div class="info-content">
	        <?php if($this->rows):?>
	        <?php foreach ($this->rows as $row):?>
	        <div class="checkbox">
	        	<input type="checkbox" name="cid[]" value="<?php echo $row->consultant_id?>" />
	        </div>
	        <div class="username">
	        	<a href="#" title="Edit <?php echo $row->username?>"><?php echo $row->username?></a>
	        </div>
	        <div class="fullname"><?php echo $row->full_name?> (<?php echo $row->title?>)</div>
	        <div class="email">
	        	<?php echo $row->email?>
	        </div>
	        <div class="job-title">
	        	<?php echo $row->job_title?>
	        </div>
	        <div class="status">
	        	<?php echo $row->status?>
	        </div>
	        <div class="admin">
	        	<?php echo $row->is_admin ? 'Yes' : 'No'?>
	        </div>
	        <div class="action">
	        	<a href="profile/edit-user" title="Edit <?php echo $row->username?>">Edit</a> | <a href="" title="Inactive <?php echo $row->username?>">Inactive</a> | <a href="#" title="Delete <?php echo $row->username?>">Delete</a>
	        </div>
            <div class="modified-date">
                <?php echo $row->updated_date?>
            </div>
            <br class="clear"/>
	        <?php endforeach;?>
	        <?php endif;?>
	        </div>
	    </div>
	</div>
</div>