<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Grey Finders | Resume Management System (RMS)</title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/theme.css')?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/style.css')?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/theme3.css')?>" />
</head>
<body>
<div id="container">
	<div id="header">
		<h2>MANAGE DOCUMENT</h2>
		<div id="topmenu">
			<ul>
				<li class="current"><a href="<?php echo $this->baseUrl('/')?>">Home</a></li>
				<li><a href="<?php echo $this->baseUrl('company')?>">Company</a></li>
				<li><a href="<?php echo $this->baseUrl('vacancy')?>">Vacancy</a></li>
				<li><a href="<?php echo $this->baseUrl('resume')?>">Resume</a></li>
			</ul>
		</div>
	</div>

	<div id="wrapper">
		<div id="content">
			<p><br/></p>